#org.apache.river.qa.harness.verifier=org.apache.river.qa.harness.SkipNonSunJDKTestVerifier
#org.apache.river.qa.harness.verifier=org.apache.river.qa.harness.SkipTestVerifier
# Test is obsolete consider if new test is required.
testClass=Constructor_AccessorTest
testCategories=activation,activation_spec
org.apache.river.qa.harness.runjiniserver=false
org.apache.river.qa.harness.runkitserver=false
