testClass=com.sun.jini.test.spec.jeri.transport.RobustnessTest
testCategories=jeri,jeri_spec
testConfiguration=<url: HttpsServerEndpointTest.config>
com.sun.jini.qa.harness.runkitserver=false 
com.sun.jini.qa.harness.runjiniserver=false
#testjvmargs=\
#-Xdebug,\
#-Xrunjdwp:transport=dt_socket+,address=8000+,server=y+,suspend=y,\
#${testjvmargs}
#-Djava.security.debug=access:failure,\
#-Dnet.jini.security.policy.PolicyFileProvider.basePolicyClass=net.jini.security.policy.ConcurrentPolicyFile,\
#-Djava.security.manager=com.sun.jini.tool.ProfilingSecurityManager,\
#${testjvmargs}
