testClass=SharedGroupNullConfigEntries
testCategories=start,start_impl

org.apache.river.start.SharedGroup.instances=3

org.apache.river.start.SharedGroup.override.0=org.apache.river.start.activationIdPreparer=null
org.apache.river.start.SharedGroup.override.1=org.apache.river.start.activationSystemPreparer=null
org.apache.river.start.SharedGroup.override.2=org.apache.river.start.exporter=null
include0=start.properties
