#/*
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#*/

QAHTTPMD		= com/sun/jini/test/spec/url/httpmd/*/*.class
QAHTTPMD_ANOTHER	= com/sun/jini/test/spec/url/httpmd/handler/*.class

QAHTTPMD_JARS = qa1-httpmd.jar qa1-httpmd-same.jar qa1-httpmd-another.jar

QAJARS     +=	$(QAHTTPMD_JARS)

qa1-httpmd.jar: jartools
	rm -f $(QAJARSDIR)/$@
	@echo Creating $@
	@cd $(CLASSDIR); $(JAR) cfv $(QAJARSDIR)/$@ -C . $(QAHTTPMD)

qa1-httpmd-same.jar: jartools qa1-httpmd.jar
	rm -f $(QAJARSDIR)/$@
	@echo Creating $@
	@cd $(QAJARSDIR); cp qa1-httpmd.jar $@

qa1-httpmd-another.jar: jartools
	rm -f $(QAJARSDIR)/$@
	@echo Creating $@
	@cd $(CLASSDIR); $(JAR) cfv $(QAJARSDIR)/$@ -C . $(QAHTTPMD_ANOTHER)

