/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

public final class CheckBoomerangs_Stub
    extends java.rmi.server.RemoteStub
    implements Boomerang, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_getObject_0;
    private static java.lang.reflect.Method $method_setChildPassed_1;
    private static java.lang.reflect.Method $method_setObject_2;
    
    static {
	try {
	    $method_getObject_0 = Boomerang.class.getMethod("getObject", new java.lang.Class[] {});
	    $method_setChildPassed_1 = Boomerang.class.getMethod("setChildPassed", new java.lang.Class[] {boolean.class});
	    $method_setObject_2 = Boomerang.class.getMethod("setObject", new java.lang.Class[] {java.lang.Object.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public CheckBoomerangs_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of getObject()
    public java.lang.Object getObject()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getObject_0, null, -8225975311538388041L);
	    return ((java.lang.Object) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setChildPassed(boolean)
    public void setChildPassed(boolean $param_boolean_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setChildPassed_1, new java.lang.Object[] {new java.lang.Boolean($param_boolean_1)}, 4082040846063646613L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setObject(Object)
    public void setObject(java.lang.Object $param_Object_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setObject_2, new java.lang.Object[] {$param_Object_1}, 456464208915235554L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
