testClass=MailboxImplNullConfigEntries
testCategories=eventmailbox,eventmailbox_impl

net.jini.event.EventMailbox.instances=6

net.jini.event.EventMailbox.override.0=org.apache.river.mercury.serverExporter=null
net.jini.event.EventMailbox.override.1=org.apache.river.mercury.initialLookupAttributes=null
net.jini.event.EventMailbox.override.2=org.apache.river.mercury.initialLookupLocators=null
net.jini.event.EventMailbox.override.3=org.apache.river.mercury.leasePeriodPolicy=null
net.jini.event.EventMailbox.override.4=org.apache.river.mercury.listenerPreparer=null
net.jini.event.EventMailbox.override.5=org.apache.river.mercury.locatorToJoinPreparer=null
include0=mercury.properties
