include0=../servicediscovery.properties
testClass=LookupDropProxyTaskRace
testCategories=servicediscovery,servicediscovery_impl,servicediscoveryevent,implservicediscovery,implservicediscoveryevent
net.jini.lookup.nLookupServices=1
net.jini.lookup.nAddLookupServices=0
net.jini.lookup.nServices=1
# To override activatable and/or persistent version of
# the lookp service. Uncomment the following items.
#com.sun.jini.qa.harness.runactivation=false
#net.jini.core.lookup.ServiceRegistrar.type=transient
