/*
 *  Licensed to the Apache Software Foundation (ASF) under one or more
 *  contributor license agreements.  See the NOTICE file distributed with
 *  this work for additional information regarding copyright ownership.
 *  The ASF licenses this file to You under the Apache License, Version 2.0
 *  (the "License"); you may not use this file except in compliance with
 *  the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package au.net.zeus.jgdms.tool.serviceproxy;

import java.io.IOException;
import java.io.StringWriter;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import javax.tools.Diagnostic;
import javax.tools.DiagnosticCollector;
import javax.tools.JavaCompiler;
import javax.tools.JavaFileObject;
import javax.tools.SimpleJavaFileObject;
import javax.tools.StandardLocation;
import javax.tools.ToolProvider;

/**
 * In-memory harness that runs {@link ServiceProxyProcessor} over a set of source
 * strings using the JDK compiler API, capturing the diagnostics and the sources
 * generated by the processor.  Self-contained: it compiles minimal stub
 * declarations of the JGDMS / Jini types the processor inspects, so the tests
 * need no JGDMS artifacts on the classpath.
 */
final class ProcessorHarness {

    /** A named piece of Java source. */
    static final class Source extends SimpleJavaFileObject {
        private final String code;
        Source(String fqn, String code) {
            super(URI.create("string:///" + fqn.replace('.', '/') + Kind.SOURCE.extension),
                  Kind.SOURCE);
            this.code = code;
        }
        @Override
        public CharSequence getCharContent(boolean ignoreEncodingErrors) {
            return code;
        }
    }

    static final class Result {
        boolean success;
        final List<Diagnostic<? extends JavaFileObject>> diagnostics = new ArrayList<>();
        /** Generated source file FQNs mapped to their content. */
        final java.util.Map<String, String> generated = new java.util.LinkedHashMap<>();
        String compilerOutput;

        boolean hasError(String needle) {
            return has(Diagnostic.Kind.ERROR, needle);
        }
        boolean hasWarning(String needle) {
            return has(Diagnostic.Kind.WARNING, needle)
                || has(Diagnostic.Kind.MANDATORY_WARNING, needle);
        }
        boolean hasAnyError() {
            for (Diagnostic<?> d : diagnostics) {
                if (d.getKind() == Diagnostic.Kind.ERROR) {
                    return true;
                }
            }
            return false;
        }
        private boolean has(Diagnostic.Kind kind, String needle) {
            for (Diagnostic<?> d : diagnostics) {
                if (d.getKind() == kind
                        && d.getMessage(null) != null
                        && d.getMessage(null).contains(needle)) {
                    return true;
                }
            }
            return false;
        }
        String allMessages() {
            StringBuilder sb = new StringBuilder();
            for (Diagnostic<?> d : diagnostics) {
                sb.append(d.getKind()).append(": ").append(d.getMessage(null)).append('\n');
            }
            return sb.toString();
        }
    }

    private final List<Source> stubs = new ArrayList<>();
    private final List<Source> sources = new ArrayList<>();
    private final List<String> options = new ArrayList<>();

    ProcessorHarness() {
        // Minimal stub declarations for the JGDMS / Jini types the processor
        // inspects by name.  java.rmi.Remote / RemoteException are real JDK
        // types and must NOT be stubbed (a source in a JDK-owned package is
        // rejected: "package exists in another module").
        addStub("net.jini.core.constraint.RemoteMethodControl",
                "package net.jini.core.constraint; public interface RemoteMethodControl {"
                + "   RemoteMethodControl setConstraints(MethodConstraints constraints);"
                + "   MethodConstraints getConstraints(); }");
        addStub("net.jini.lookup.ServiceProxyAccessor",
                "package net.jini.lookup; public interface ServiceProxyAccessor {}");
        addStub("net.jini.lookup.ServiceAttributesAccessor",
                "package net.jini.lookup; public interface ServiceAttributesAccessor {}");
        addStub("net.jini.lookup.ServiceIDAccessor",
                "package net.jini.lookup; public interface ServiceIDAccessor {}");
        addStub("net.jini.export.CodebaseAccessor",
                "package net.jini.export; public interface CodebaseAccessor {}");
        addStub("net.jini.admin.Administrable",
                "package net.jini.admin; public interface Administrable {}");
        addStub("net.jini.admin.JoinAdmin",
                "package net.jini.admin; public interface JoinAdmin {}");
        addStub("org.apache.river.admin.DestroyAdmin",
                "package org.apache.river.admin; public interface DestroyAdmin {}");
        addStub("net.jini.id.Uuid", "package net.jini.id; public interface Uuid {}");
        addStub("net.jini.core.constraint.MethodConstraints",
                "package net.jini.core.constraint; public interface MethodConstraints {}");
        addStub("org.apache.river.api.io.AtomicSerial",
                "package org.apache.river.api.io; import java.lang.annotation.*;"
                + " @Retention(RetentionPolicy.RUNTIME) @Target(ElementType.TYPE)"
                + " public @interface AtomicSerial {"
                + "   @Retention(RetentionPolicy.RUNTIME) @Target(ElementType.TYPE)"
                + "   @interface Stateless {}"
                + "   interface GetArg {} }");
        // Stub AbstractSmartProxy with the members the generated proxy references:
        // a server field, getReferentUuid(), and a ConstrainableSmartProxy base
        // exposing the (server, proxyID, constraints) and (GetArg) constructors
        // plus RemoteMethodControl.  This lets the generated proxy actually
        // compile, proving signature/constructor fidelity.
        addStub("au.net.zeus.jgdms.proxy.AbstractSmartProxy",
                "package au.net.zeus.jgdms.proxy;"
                + " import net.jini.id.Uuid;"
                + " import net.jini.core.constraint.MethodConstraints;"
                + " import net.jini.core.constraint.RemoteMethodControl;"
                + " import org.apache.river.api.io.AtomicSerial.GetArg;"
                + " public abstract class AbstractSmartProxy {"
                + "   protected final Object server;"
                + "   protected AbstractSmartProxy(Object server, Uuid proxyID) { this.server = server; }"
                + "   protected AbstractSmartProxy(GetArg arg) { this.server = null; }"
                + "   public final Uuid getReferentUuid() { return null; }"
                + "   public static abstract class ConstrainableSmartProxy extends AbstractSmartProxy"
                + "       implements RemoteMethodControl {"
                + "     protected ConstrainableSmartProxy(Object server, Uuid proxyID, MethodConstraints c) { super(server, proxyID); }"
                + "     protected ConstrainableSmartProxy(GetArg arg) { super(arg); }"
                + "     public MethodConstraints getConstraints() { return null; }"
                + "   } }");
        // The annotations under test (SOURCE-retained; the real ones live in the
        // annotations module, restated here so the harness is standalone).
        addStub("au.net.zeus.jgdms.service.annotation.JiniService",
                "package au.net.zeus.jgdms.service.annotation;"
                + " import java.lang.annotation.*;"
                + " @Retention(RetentionPolicy.SOURCE) @Target(ElementType.TYPE)"
                + " public @interface JiniService {"
                + "   Class<?> protocol() default Void.class;"
                + "   String component() default \"\";"
                + "   Generate[] generate() default { Generate.BACKEND, Generate.PROXY, Generate.WRAPPER };"
                + "   enum Generate { BACKEND, PROXY, WRAPPER } }");
        addStub("au.net.zeus.jgdms.service.annotation.SmartProxy",
                "package au.net.zeus.jgdms.service.annotation;"
                + " import java.lang.annotation.*;"
                + " @Retention(RetentionPolicy.SOURCE) @Target(ElementType.TYPE)"
                + " public @interface SmartProxy {"
                + "   Class<?> api();"
                + "   Class<?> protocol() default Void.class; }");
    }

    ProcessorHarness addStub(String fqn, String code) {
        stubs.add(new Source(fqn, code));
        return this;
    }

    ProcessorHarness add(String fqn, String code) {
        sources.add(new Source(fqn, code));
        return this;
    }

    ProcessorHarness option(String opt) {
        options.add(opt);
        return this;
    }

    Result run() {
        JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();
        DiagnosticCollector<JavaFileObject> diags = new DiagnosticCollector<>();
        CapturingFileManager fm = new CapturingFileManager(
                compiler.getStandardFileManager(diags, null, null));

        List<JavaFileObject> all = new ArrayList<>();
        all.addAll(stubs);
        all.addAll(sources);

        List<String> opts = new ArrayList<>();
        opts.add("-proc:only"); // run processors, do not compile bytecode
        opts.addAll(options);

        StringWriter out = new StringWriter();
        JavaCompiler.CompilationTask task = compiler.getTask(
                out, fm, diags, opts, null, all);
        task.setProcessors(List.of(new ServiceProxyProcessor()));

        Result r = new Result();
        r.success = task.call();
        r.diagnostics.addAll(diags.getDiagnostics());
        r.compilerOutput = out.toString();
        r.generated.putAll(fm.generatedSources());
        return r;
    }

    /**
     * Full compilation (to bytecode, processors off) of the stubs, the original
     * sources, and every processor-generated source in {@code result}.  Proves
     * that the generated code actually compiles -- the ultimate fidelity check
     * for the emitted forwarding proxy.
     */
    Result compileGenerated(Result result) {
        JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();
        DiagnosticCollector<JavaFileObject> diags = new DiagnosticCollector<>();
        CapturingFileManager fm = new CapturingFileManager(
                compiler.getStandardFileManager(diags, null, null));

        List<JavaFileObject> all = new ArrayList<>();
        all.addAll(stubs);
        all.addAll(sources);
        result.generated.forEach((fqn, code) -> all.add(new Source(fqn, code)));

        StringWriter out = new StringWriter();
        // -proc:none: do not re-run the processor; just type-check + compile.
        JavaCompiler.CompilationTask task = compiler.getTask(
                out, fm, diags, List.of("-proc:none"), null, all);

        Result r = new Result();
        r.success = task.call();
        r.diagnostics.addAll(diags.getDiagnostics());
        r.compilerOutput = out.toString();
        return r;
    }

    /** File manager that captures processor-generated source into memory. */
    private static final class CapturingFileManager
            extends javax.tools.ForwardingJavaFileManager<javax.tools.StandardJavaFileManager> {

        private final java.util.Map<String, GeneratedSource> generated =
                new java.util.LinkedHashMap<>();

        CapturingFileManager(javax.tools.StandardJavaFileManager fm) {
            super(fm);
        }

        @Override
        public JavaFileObject getJavaFileForOutput(Location location, String className,
                JavaFileObject.Kind kind, javax.tools.FileObject sibling) {
            if (location == StandardLocation.SOURCE_OUTPUT
                    && kind == JavaFileObject.Kind.SOURCE) {
                GeneratedSource gs = new GeneratedSource(className);
                generated.put(className, gs);
                return gs;
            }
            // CLASS_OUTPUT (bytecode from compileGenerated): discard to memory so
            // nothing touches disk and no output directory is required.
            return new DiscardingOutput(className, kind);
        }

        java.util.Map<String, String> generatedSources() {
            java.util.Map<String, String> out = new java.util.LinkedHashMap<>();
            generated.forEach((k, v) -> out.put(k, v.content()));
            return out;
        }
    }

    private static final class GeneratedSource extends SimpleJavaFileObject {
        private final java.io.StringWriter writer = new java.io.StringWriter();
        GeneratedSource(String fqn) {
            super(URI.create("mem:///" + fqn.replace('.', '/') + Kind.SOURCE.extension),
                  Kind.SOURCE);
        }
        @Override
        public java.io.Writer openWriter() {
            return writer;
        }
        @Override
        public CharSequence getCharContent(boolean ignoreEncodingErrors) {
            // The compiler re-reads generated sources in the next round to parse
            // them; return what the processor wrote.
            return writer.toString();
        }
        String content() {
            return writer.toString();
        }
    }

    /** A sink for compiler bytecode output that discards everything to memory. */
    private static final class DiscardingOutput extends SimpleJavaFileObject {
        private final java.io.ByteArrayOutputStream bytes = new java.io.ByteArrayOutputStream();
        DiscardingOutput(String fqn, Kind kind) {
            super(URI.create("mem:///" + fqn.replace('.', '/') + kind.extension), kind);
        }
        @Override
        public java.io.OutputStream openOutputStream() {
            return bytes;
        }
    }
}
