/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package au.net.zeus.jgdms.bae;

import org.junit.Test;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;
import au.net.zeus.jgdms.api.codebase.ClinitVerdict;

import static org.junit.Assert.assertEquals;

/**
 * Unit tests for {@link ClinitBlockingVisitor} focusing on:
 * <ul>
 *   <li>{@link ClinitVerdict#BLOCKING} — unguarded blocking paths reachable
 *       from {@code <clinit>}</li>
 *   <li>{@link ClinitVerdict#BLOCKING_GUARDED} — blocking paths preceded by a
 *       {@code SecurityManager.checkXxx()} or
 *       {@code AccessController.checkPermission()} call</li>
 *   <li>New Java API blocking sinks: {@code FileInputStream.read},
 *       {@code Selector.select}, {@code SocketChannel.read},
 *       {@code StampedLock.writeLock}, {@code CompletableFuture.join},
 *       {@code Process.waitFor}, {@code LinkedTransferQueue.take},
 *       {@code DatagramSocket.receive}</li>
 *   <li>DirtyChai-specific sinks: {@code sun.nio.ch.Poller.poll} and
 *       {@code sun.nio.ch.Poller.pollSelector}</li>
 * </ul>
 *
 * <p>Each test generates a minimal synthetic class via ASM that exhibits the
 * specific bytecode pattern under test.
 *
 * @author GitHub Copilot
 */
public class ClinitBlockingVisitorTest {

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    /** Builds class bytes for a class whose {@code <clinit>} invokes {@code target}. */
    private static byte[] buildClinitCallingMethod(
            String owner, String name, String descriptor,
            int invokeOpcode) {

        ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_FRAMES);
        cw.visit(Opcodes.V11,
                 Opcodes.ACC_PUBLIC | Opcodes.ACC_SUPER,
                 "au/net/zeus/jgdms/bae/test/Synthetic",
                 null, "java/lang/Object", null);

        MethodVisitor mv = cw.visitMethod(
                Opcodes.ACC_STATIC, "<clinit>", "()V", null, null);
        mv.visitCode();
        mv.visitMethodInsn(invokeOpcode, owner, name, descriptor, false);
        mv.visitInsn(Opcodes.RETURN);
        mv.visitMaxs(0, 0);
        mv.visitEnd();
        cw.visitEnd();
        return cw.toByteArray();
    }

    /**
     * Builds a class whose {@code <clinit>} calls {@code SecurityManager.checkXxx}
     * (a permission guard) and then calls the given blocking method.
     *
     * <p>The generated bytecode looks like:
     * <pre>
     *   static {
     *       new SecurityManager().checkPermission(new RuntimePermission("test"));
     *       // ...blocking call...
     *   }
     * </pre>
     *
     * <p>In the call graph both the guard and the blocking call appear as direct
     * callees of {@code <clinit>}, which is sufficient for
     * {@link ClinitBlockingVisitor} to detect {@code BLOCKING_GUARDED}.
     */
    private static byte[] buildGuardedClinitCallingMethod(
            String blockingOwner, String blockingName, String blockingDescriptor,
            int invokeOpcode) {

        ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_FRAMES);
        cw.visit(Opcodes.V11,
                 Opcodes.ACC_PUBLIC | Opcodes.ACC_SUPER,
                 "au/net/zeus/jgdms/bae/test/Synthetic",
                 null, "java/lang/Object", null);

        MethodVisitor mv = cw.visitMethod(
                Opcodes.ACC_STATIC, "<clinit>", "()V", null, null);
        mv.visitCode();

        // Emit: new SecurityManager().checkPermission(new RuntimePermission("test"))
        mv.visitTypeInsn(Opcodes.NEW, "java/lang/SecurityManager");
        mv.visitInsn(Opcodes.DUP);
        mv.visitMethodInsn(Opcodes.INVOKESPECIAL,
                "java/lang/SecurityManager", "<init>", "()V", false);
        mv.visitTypeInsn(Opcodes.NEW, "java/lang/RuntimePermission");
        mv.visitInsn(Opcodes.DUP);
        mv.visitLdcInsn("test");
        mv.visitMethodInsn(Opcodes.INVOKESPECIAL,
                "java/lang/RuntimePermission", "<init>",
                "(Ljava/lang/String;)V", false);
        mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL,
                "java/lang/SecurityManager", "checkPermission",
                "(Ljava/security/Permission;)V", false);

        // Emit the blocking call
        mv.visitMethodInsn(invokeOpcode,
                blockingOwner, blockingName, blockingDescriptor, false);

        mv.visitInsn(Opcodes.RETURN);
        mv.visitMaxs(4, 0);
        mv.visitEnd();
        cw.visitEnd();
        return cw.toByteArray();
    }

    private static ClinitVerdict analyze(byte[] classBytes) throws Exception {
        java.util.Map<String, java.util.Set<String>> callGraph =
                new java.util.HashMap<>();
        java.util.Map<String, Boolean> isNativeMap = new java.util.HashMap<>();
        String[] clinitOwner = { null };
        ClinitBlockingVisitor.indexClass(classBytes, callGraph, isNativeMap, clinitOwner);
        if (clinitOwner[0] == null) {
            return ClinitVerdict.CLEAN;
        }
        return ClinitBlockingVisitor.analyzeClinitReachability(
                clinitOwner[0], callGraph, isNativeMap, 20).verdict;
    }

    // -------------------------------------------------------------------------
    // Existing sinks — regression: still BLOCKING
    // -------------------------------------------------------------------------

    @Test
    public void testThreadSleep_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "java/lang/Thread", "sleep", "(J)V",
                Opcodes.INVOKESTATIC);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    @Test
    public void testObjectWait_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "java/lang/Object", "wait", "()V",
                Opcodes.INVOKEVIRTUAL);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    @Test
    public void testLockSupportPark_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "java/util/concurrent/locks/LockSupport", "park", "()V",
                Opcodes.INVOKESTATIC);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    // -------------------------------------------------------------------------
    // New Java API sinks
    // -------------------------------------------------------------------------

    @Test
    public void testFileInputStreamRead_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "java/io/FileInputStream", "read", "()I",
                Opcodes.INVOKEVIRTUAL);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    @Test
    public void testFileOutputStreamWrite_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "java/io/FileOutputStream", "write", "([B)V",
                Opcodes.INVOKEVIRTUAL);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    @Test
    public void testReaderRead_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "java/io/Reader", "read", "([CII)I",
                Opcodes.INVOKEVIRTUAL);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    @Test
    public void testPipedInputStreamRead_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "java/io/PipedInputStream", "read", "()I",
                Opcodes.INVOKEVIRTUAL);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    @Test
    public void testSelectorSelect_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "java/nio/channels/Selector", "select", "()I",
                Opcodes.INVOKEVIRTUAL);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    @Test
    public void testSocketChannelRead_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "java/nio/channels/SocketChannel", "read",
                "(Ljava/nio/ByteBuffer;)I",
                Opcodes.INVOKEVIRTUAL);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    @Test
    public void testFileChannelLock_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "java/nio/channels/FileChannel", "lock",
                "()Ljava/nio/channels/FileLock;",
                Opcodes.INVOKEVIRTUAL);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    @Test
    public void testProcessWaitFor_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "java/lang/Process", "waitFor", "()I",
                Opcodes.INVOKEVIRTUAL);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    @Test
    public void testCompletableFutureJoin_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "java/util/concurrent/CompletableFuture", "join",
                "()Ljava/lang/Object;",
                Opcodes.INVOKEVIRTUAL);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    @Test
    public void testCompletableFutureGet_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "java/util/concurrent/CompletableFuture", "get",
                "()Ljava/lang/Object;",
                Opcodes.INVOKEVIRTUAL);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    @Test
    public void testStampedLockWriteLock_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "java/util/concurrent/locks/StampedLock", "writeLock", "()J",
                Opcodes.INVOKEVIRTUAL);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    @Test
    public void testStampedLockReadLock_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "java/util/concurrent/locks/StampedLock", "readLock", "()J",
                Opcodes.INVOKEVIRTUAL);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    @Test
    public void testLinkedTransferQueueTake_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "java/util/concurrent/LinkedTransferQueue", "take",
                "()Ljava/lang/Object;",
                Opcodes.INVOKEVIRTUAL);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    @Test
    public void testLinkedTransferQueueTransfer_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "java/util/concurrent/LinkedTransferQueue", "transfer",
                "(Ljava/lang/Object;)V",
                Opcodes.INVOKEVIRTUAL);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    @Test
    public void testDatagramSocketReceive_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "java/net/DatagramSocket", "receive",
                "(Ljava/net/DatagramPacket;)V",
                Opcodes.INVOKEVIRTUAL);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    // -------------------------------------------------------------------------
    // DirtyChai-specific sinks
    // -------------------------------------------------------------------------

    @Test
    public void testPollerPoll_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "sun/nio/ch/Poller", "poll",
                "(IIJLjava/util/function/BooleanSupplier;)V",
                Opcodes.INVOKESTATIC);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    @Test
    public void testPollerPollSelector_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "sun/nio/ch/Poller", "pollSelector", "(IJ)V",
                Opcodes.INVOKESTATIC);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    // -------------------------------------------------------------------------
    // BLOCKING_GUARDED — permission guard before blocking call
    // -------------------------------------------------------------------------

    @Test
    public void testThreadSleepAfterSmCheckPermission_isBlockingGuarded()
            throws Exception {
        byte[] bytes = buildGuardedClinitCallingMethod(
                "java/lang/Thread", "sleep", "(J)V",
                Opcodes.INVOKESTATIC);
        assertEquals(ClinitVerdict.BLOCKING_GUARDED, analyze(bytes));
    }

    @Test
    public void testSocketConnectAfterSmCheckPermission_isBlockingGuarded()
            throws Exception {
        byte[] bytes = buildGuardedClinitCallingMethod(
                "java/net/Socket", "connect",
                "(Ljava/net/SocketAddress;)V",
                Opcodes.INVOKEVIRTUAL);
        assertEquals(ClinitVerdict.BLOCKING_GUARDED, analyze(bytes));
    }

    @Test
    public void testSelectorSelectAfterSmCheckPermission_isBlockingGuarded()
            throws Exception {
        byte[] bytes = buildGuardedClinitCallingMethod(
                "java/nio/channels/Selector", "select", "()I",
                Opcodes.INVOKEVIRTUAL);
        assertEquals(ClinitVerdict.BLOCKING_GUARDED, analyze(bytes));
    }

    @Test
    public void testPollerPollAfterSmCheckPermission_isBlockingGuarded()
            throws Exception {
        byte[] bytes = buildGuardedClinitCallingMethod(
                "sun/nio/ch/Poller", "poll",
                "(IIJLjava/util/function/BooleanSupplier;)V",
                Opcodes.INVOKESTATIC);
        assertEquals(ClinitVerdict.BLOCKING_GUARDED, analyze(bytes));
    }

    // -------------------------------------------------------------------------
    // BlockingSinkRegistry.isPermissionGuard — unit checks
    // -------------------------------------------------------------------------

    @Test
    public void testIsPermissionGuard_SmCheckPermission_isTrue() {
        assertTrue(BlockingSinkRegistry.isPermissionGuard(
                "java/lang/SecurityManager", "checkPermission",
                "(Ljava/security/Permission;)V"));
    }

    @Test
    public void testIsPermissionGuard_SmCheckConnect_isTrue() {
        assertTrue(BlockingSinkRegistry.isPermissionGuard(
                "java/lang/SecurityManager", "checkConnect",
                "(Ljava/lang/String;I)V"));
    }

    @Test
    public void testIsPermissionGuard_SmCheckRead_isTrue() {
        assertTrue(BlockingSinkRegistry.isPermissionGuard(
                "java/lang/SecurityManager", "checkRead",
                "(Ljava/lang/String;)V"));
    }

    @Test
    public void testIsPermissionGuard_AcCheckPermission_isTrue() {
        assertTrue(BlockingSinkRegistry.isPermissionGuard(
                "java/security/AccessController", "checkPermission",
                "(Ljava/security/Permission;)V"));
    }

    @Test
    public void testIsPermissionGuard_DoPrivileged_isFalse() {
        assertFalse(BlockingSinkRegistry.isPermissionGuard(
                "java/security/AccessController", "doPrivileged",
                "(Ljava/security/PrivilegedAction;)Ljava/lang/Object;"));
    }

    @Test
    public void testIsPermissionGuard_ThreadSleep_isFalse() {
        assertFalse(BlockingSinkRegistry.isPermissionGuard(
                "java/lang/Thread", "sleep", "(J)V"));
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private static void assertTrue(boolean condition) {
        assertEquals(true, condition);
    }

    private static void assertFalse(boolean condition) {
        assertEquals(false, condition);
    }
}
