/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package au.net.zeus.jgdms.bae;

import org.junit.Test;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;
import au.net.zeus.jgdms.api.codebase.ClinitVerdict;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

/**
 * Unit tests for {@link ClinitBlockingVisitor} focusing on:
 * <ul>
 *   <li>{@link ClinitVerdict#BLOCKING} — unguarded blocking paths reachable
 *       from {@code <clinit>}</li>
 *   <li>{@link ClinitVerdict#BLOCKING_GUARDED} — blocking paths preceded by a
 *       {@code SecurityManager.checkXxx()} or
 *       {@code AccessController.checkPermission()} call</li>
 *   <li>New Java API blocking sinks: {@code FileInputStream.read},
 *       {@code Selector.select}, {@code SocketChannel.read},
 *       {@code StampedLock.writeLock}, {@code CompletableFuture.join},
 *       {@code Process.waitFor}, {@code LinkedTransferQueue.take},
 *       {@code DatagramSocket.receive}</li>
 *   <li>DirtyChai-specific sinks: {@code sun.nio.ch.Poller.poll} and
 *       {@code sun.nio.ch.Poller.pollSelector}</li>
 * </ul>
 *
 * <p>Each test generates a minimal synthetic class via ASM that exhibits the
 * specific bytecode pattern under test.
 *
 * @author GitHub Copilot
 */
public class ClinitBlockingVisitorTest {

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    /** Builds class bytes for a class whose {@code <clinit>} invokes {@code target}. */
    private static byte[] buildClinitCallingMethod(
            String owner, String name, String descriptor,
            int invokeOpcode) {

        ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_FRAMES);
        cw.visit(Opcodes.V11,
                 Opcodes.ACC_PUBLIC | Opcodes.ACC_SUPER,
                 "au/net/zeus/jgdms/bae/test/Synthetic",
                 null, "java/lang/Object", null);

        MethodVisitor mv = cw.visitMethod(
                Opcodes.ACC_STATIC, "<clinit>", "()V", null, null);
        mv.visitCode();
        mv.visitMethodInsn(invokeOpcode, owner, name, descriptor, false);
        mv.visitInsn(Opcodes.RETURN);
        mv.visitMaxs(0, 0);
        mv.visitEnd();
        cw.visitEnd();
        return cw.toByteArray();
    }

    /**
     * Builds a class whose {@code <clinit>} calls {@code SecurityManager.checkXxx}
     * (a permission guard) and then calls the given blocking method.
     *
     * <p>The generated bytecode looks like:
     * <pre>
     *   static {
     *       new SecurityManager().checkPermission(new RuntimePermission("test"));
     *       // ...blocking call...
     *   }
     * </pre>
     *
     * <p>In the call graph both the guard and the blocking call appear as direct
     * callees of {@code <clinit>}, which is sufficient for
     * {@link ClinitBlockingVisitor} to detect {@code BLOCKING_GUARDED}.
     */
    private static byte[] buildGuardedClinitCallingMethod(
            String blockingOwner, String blockingName, String blockingDescriptor,
            int invokeOpcode) {

        ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_FRAMES);
        cw.visit(Opcodes.V11,
                 Opcodes.ACC_PUBLIC | Opcodes.ACC_SUPER,
                 "au/net/zeus/jgdms/bae/test/Synthetic",
                 null, "java/lang/Object", null);

        MethodVisitor mv = cw.visitMethod(
                Opcodes.ACC_STATIC, "<clinit>", "()V", null, null);
        mv.visitCode();

        // Emit: new SecurityManager().checkPermission(new RuntimePermission("test"))
        mv.visitTypeInsn(Opcodes.NEW, "java/lang/SecurityManager");
        mv.visitInsn(Opcodes.DUP);
        mv.visitMethodInsn(Opcodes.INVOKESPECIAL,
                "java/lang/SecurityManager", "<init>", "()V", false);
        mv.visitTypeInsn(Opcodes.NEW, "java/lang/RuntimePermission");
        mv.visitInsn(Opcodes.DUP);
        mv.visitLdcInsn("test");
        mv.visitMethodInsn(Opcodes.INVOKESPECIAL,
                "java/lang/RuntimePermission", "<init>",
                "(Ljava/lang/String;)V", false);
        mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL,
                "java/lang/SecurityManager", "checkPermission",
                "(Ljava/security/Permission;)V", false);

        // Emit the blocking call
        mv.visitMethodInsn(invokeOpcode,
                blockingOwner, blockingName, blockingDescriptor, false);

        mv.visitInsn(Opcodes.RETURN);
        mv.visitMaxs(4, 0);
        mv.visitEnd();
        cw.visitEnd();
        return cw.toByteArray();
    }

    /**
     * Builds a class whose {@code <clinit>} reads a static field of
     * {@code fieldOwner} via {@code GETSTATIC}.  Referencing a static field
     * triggers the owner class's {@code <clinit>}, so this models a static-
     * field-triggered initialization edge into another class.
     */
    private static byte[] buildClinitReadingStaticField(
            String className, String fieldOwner,
            String fieldName, String fieldDescriptor) {

        ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_FRAMES);
        cw.visit(Opcodes.V11,
                 Opcodes.ACC_PUBLIC | Opcodes.ACC_SUPER,
                 className,
                 null, "java/lang/Object", null);

        MethodVisitor mv = cw.visitMethod(
                Opcodes.ACC_STATIC, "<clinit>", "()V", null, null);
        mv.visitCode();
        mv.visitFieldInsn(Opcodes.GETSTATIC, fieldOwner, fieldName, fieldDescriptor);
        // discard the value so the synthetic stub is well-formed enough for ASM
        mv.visitInsn(Opcodes.POP);
        mv.visitInsn(Opcodes.RETURN);
        mv.visitMaxs(0, 0);
        mv.visitEnd();
        cw.visitEnd();
        return cw.toByteArray();
    }

    private static ClinitVerdict analyze(byte[] classBytes) throws Exception {
        java.util.Map<String, java.util.Set<String>> callGraph =
                new java.util.HashMap<>();
        java.util.Map<String, Boolean> isNativeMap = new java.util.HashMap<>();
        String[] clinitOwner = { null };
        ClinitBlockingVisitor.indexClass(classBytes, callGraph, isNativeMap, clinitOwner);
        if (clinitOwner[0] == null) {
            return ClinitVerdict.CLEAN;
        }
        return ClinitBlockingVisitor.analyzeClinitReachability(
                clinitOwner[0], callGraph, isNativeMap, 20).verdict;
    }

    // -------------------------------------------------------------------------
    // Existing sinks — regression: still BLOCKING
    // -------------------------------------------------------------------------

    @Test
    public void testThreadSleep_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "java/lang/Thread", "sleep", "(J)V",
                Opcodes.INVOKESTATIC);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    @Test
    public void testObjectWait_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "java/lang/Object", "wait", "()V",
                Opcodes.INVOKEVIRTUAL);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    @Test
    public void testLockSupportPark_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "java/util/concurrent/locks/LockSupport", "park", "()V",
                Opcodes.INVOKESTATIC);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    // -------------------------------------------------------------------------
    // New Java API sinks
    // -------------------------------------------------------------------------

    @Test
    public void testFileInputStreamRead_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "java/io/FileInputStream", "read", "()I",
                Opcodes.INVOKEVIRTUAL);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    @Test
    public void testFileOutputStreamWrite_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "java/io/FileOutputStream", "write", "([B)V",
                Opcodes.INVOKEVIRTUAL);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    @Test
    public void testReaderRead_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "java/io/Reader", "read", "([CII)I",
                Opcodes.INVOKEVIRTUAL);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    @Test
    public void testPipedInputStreamRead_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "java/io/PipedInputStream", "read", "()I",
                Opcodes.INVOKEVIRTUAL);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    @Test
    public void testSelectorSelect_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "java/nio/channels/Selector", "select", "()I",
                Opcodes.INVOKEVIRTUAL);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    @Test
    public void testSocketChannelRead_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "java/nio/channels/SocketChannel", "read",
                "(Ljava/nio/ByteBuffer;)I",
                Opcodes.INVOKEVIRTUAL);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    @Test
    public void testFileChannelLock_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "java/nio/channels/FileChannel", "lock",
                "()Ljava/nio/channels/FileLock;",
                Opcodes.INVOKEVIRTUAL);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    @Test
    public void testProcessWaitFor_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "java/lang/Process", "waitFor", "()I",
                Opcodes.INVOKEVIRTUAL);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    @Test
    public void testCompletableFutureJoin_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "java/util/concurrent/CompletableFuture", "join",
                "()Ljava/lang/Object;",
                Opcodes.INVOKEVIRTUAL);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    @Test
    public void testCompletableFutureGet_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "java/util/concurrent/CompletableFuture", "get",
                "()Ljava/lang/Object;",
                Opcodes.INVOKEVIRTUAL);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    @Test
    public void testStampedLockWriteLock_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "java/util/concurrent/locks/StampedLock", "writeLock", "()J",
                Opcodes.INVOKEVIRTUAL);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    @Test
    public void testStampedLockReadLock_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "java/util/concurrent/locks/StampedLock", "readLock", "()J",
                Opcodes.INVOKEVIRTUAL);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    @Test
    public void testLinkedTransferQueueTake_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "java/util/concurrent/LinkedTransferQueue", "take",
                "()Ljava/lang/Object;",
                Opcodes.INVOKEVIRTUAL);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    @Test
    public void testLinkedTransferQueueTransfer_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "java/util/concurrent/LinkedTransferQueue", "transfer",
                "(Ljava/lang/Object;)V",
                Opcodes.INVOKEVIRTUAL);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    @Test
    public void testDatagramSocketReceive_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "java/net/DatagramSocket", "receive",
                "(Ljava/net/DatagramPacket;)V",
                Opcodes.INVOKEVIRTUAL);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    // -------------------------------------------------------------------------
    // DirtyChai-specific sinks
    // -------------------------------------------------------------------------

    @Test
    public void testPollerPoll_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "sun/nio/ch/Poller", "poll",
                "(IIJLjava/util/function/BooleanSupplier;)V",
                Opcodes.INVOKESTATIC);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    @Test
    public void testPollerPollSelector_isBlocking() throws Exception {
        byte[] bytes = buildClinitCallingMethod(
                "sun/nio/ch/Poller", "pollSelector", "(IJ)V",
                Opcodes.INVOKESTATIC);
        assertEquals(ClinitVerdict.BLOCKING, analyze(bytes));
    }

    // -------------------------------------------------------------------------
    // Static-field-triggered <clinit> edge (GETSTATIC / PUTSTATIC)
    // -------------------------------------------------------------------------

    /**
     * Class A's {@code <clinit>} reads a static field of class B (a
     * {@code GETSTATIC}); B's {@code <clinit>} calls a blocking sink
     * ({@code Thread.sleep}).  Reading B's static field triggers B's
     * {@code <clinit>}, so the blocking path must be reachable from A and the
     * verdict must be {@link ClinitVerdict#BLOCKING}.
     */
    @Test
    public void testStaticFieldReferenceTriggersBlockingClinit_isBlocking()
            throws Exception {
        String classA = "au/net/zeus/jgdms/bae/test/A";
        String classB = "au/net/zeus/jgdms/bae/test/B";

        byte[] aBytes = buildClinitReadingStaticField(
                classA, classB, "FLAG", "I");

        // B.<clinit> calls Thread.sleep (a registered blocking sink).
        ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_FRAMES);
        cw.visit(Opcodes.V11,
                 Opcodes.ACC_PUBLIC | Opcodes.ACC_SUPER,
                 classB, null, "java/lang/Object", null);
        // declare the static field that A references
        cw.visitField(Opcodes.ACC_PUBLIC | Opcodes.ACC_STATIC,
                "FLAG", "I", null, null).visitEnd();
        MethodVisitor mv = cw.visitMethod(
                Opcodes.ACC_STATIC, "<clinit>", "()V", null, null);
        mv.visitCode();
        mv.visitMethodInsn(Opcodes.INVOKESTATIC,
                "java/lang/Thread", "sleep", "(J)V", false);
        mv.visitInsn(Opcodes.RETURN);
        mv.visitMaxs(0, 0);
        mv.visitEnd();
        cw.visitEnd();
        byte[] bBytes = cw.toByteArray();

        java.util.Map<String, java.util.Set<String>> callGraph =
                new java.util.HashMap<>();
        java.util.Map<String, Boolean> isNativeMap = new java.util.HashMap<>();
        ClinitBlockingVisitor.indexClass(aBytes, callGraph, isNativeMap, new String[]{null});
        ClinitBlockingVisitor.indexClass(bBytes, callGraph, isNativeMap, new String[]{null});

        ClinitVerdict v = ClinitBlockingVisitor.analyzeClinitReachability(
                classA, callGraph, isNativeMap, 20).verdict;
        assertEquals(ClinitVerdict.BLOCKING, v);
    }

    /**
     * Sanity check: without the {@code visitFieldInsn} edge, a {@code <clinit>}
     * that only reads a static field of a class with a clean {@code <clinit>}
     * stays CLEAN.
     */
    @Test
    public void testStaticFieldReferenceToCleanClinit_isClean()
            throws Exception {
        String classA = "au/net/zeus/jgdms/bae/test/CleanA";
        String classB = "au/net/zeus/jgdms/bae/test/CleanB";

        byte[] aBytes = buildClinitReadingStaticField(
                classA, classB, "FLAG", "I");

        // B.<clinit> does nothing blocking.
        ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_FRAMES);
        cw.visit(Opcodes.V11,
                 Opcodes.ACC_PUBLIC | Opcodes.ACC_SUPER,
                 classB, null, "java/lang/Object", null);
        cw.visitField(Opcodes.ACC_PUBLIC | Opcodes.ACC_STATIC,
                "FLAG", "I", null, null).visitEnd();
        MethodVisitor mv = cw.visitMethod(
                Opcodes.ACC_STATIC, "<clinit>", "()V", null, null);
        mv.visitCode();
        mv.visitInsn(Opcodes.RETURN);
        mv.visitMaxs(0, 0);
        mv.visitEnd();
        cw.visitEnd();
        byte[] bBytes = cw.toByteArray();

        java.util.Map<String, java.util.Set<String>> callGraph =
                new java.util.HashMap<>();
        java.util.Map<String, Boolean> isNativeMap = new java.util.HashMap<>();
        ClinitBlockingVisitor.indexClass(aBytes, callGraph, isNativeMap, new String[]{null});
        ClinitBlockingVisitor.indexClass(bBytes, callGraph, isNativeMap, new String[]{null});

        ClinitVerdict v = ClinitBlockingVisitor.analyzeClinitReachability(
                classA, callGraph, isNativeMap, 20).verdict;
        assertEquals(ClinitVerdict.CLEAN, v);
    }

    // -------------------------------------------------------------------------
    // BLOCKING_GUARDED — permission guard before blocking call
    // -------------------------------------------------------------------------

    @Test
    public void testThreadSleepAfterSmCheckPermission_isBlockingGuarded()
            throws Exception {
        byte[] bytes = buildGuardedClinitCallingMethod(
                "java/lang/Thread", "sleep", "(J)V",
                Opcodes.INVOKESTATIC);
        assertEquals(ClinitVerdict.BLOCKING_GUARDED, analyze(bytes));
    }

    @Test
    public void testSocketConnectAfterSmCheckPermission_isBlockingGuarded()
            throws Exception {
        byte[] bytes = buildGuardedClinitCallingMethod(
                "java/net/Socket", "connect",
                "(Ljava/net/SocketAddress;)V",
                Opcodes.INVOKEVIRTUAL);
        assertEquals(ClinitVerdict.BLOCKING_GUARDED, analyze(bytes));
    }

    @Test
    public void testSelectorSelectAfterSmCheckPermission_isBlockingGuarded()
            throws Exception {
        byte[] bytes = buildGuardedClinitCallingMethod(
                "java/nio/channels/Selector", "select", "()I",
                Opcodes.INVOKEVIRTUAL);
        assertEquals(ClinitVerdict.BLOCKING_GUARDED, analyze(bytes));
    }

    @Test
    public void testPollerPollAfterSmCheckPermission_isBlockingGuarded()
            throws Exception {
        byte[] bytes = buildGuardedClinitCallingMethod(
                "sun/nio/ch/Poller", "poll",
                "(IIJLjava/util/function/BooleanSupplier;)V",
                Opcodes.INVOKESTATIC);
        assertEquals(ClinitVerdict.BLOCKING_GUARDED, analyze(bytes));
    }

    // -------------------------------------------------------------------------
    // indexClass fail-secure Throwable handling (Fix 2)
    // -------------------------------------------------------------------------

    /**
     * Builds a class whose header/constant-pool/class-structure is fully
     * valid — so ASM's {@code visit()} callback fires and sets the owning
     * class name — but whose {@code <clinit>} body is corrupted: the
     * trailing {@code RETURN} (0xB1) is overwritten with {@code TABLESWITCH}
     * (0xAA), whose garbage default/low/high operands (whatever bytes
     * happen to follow) drive ASM's instruction decoder to read past the end
     * of the backing byte array.
     *
     * <p>This deterministically reproduces "parses the header cleanly, then
     * throws mid-method-body" — the scenario the fail-secure contract on
     * {@link ClinitBlockingVisitor#indexClass} targets (the production
     * concern is a {@link StackOverflowError} from unbounded ASM recursion,
     * but any {@link Throwable} thrown after {@code visit()} exercises the
     * identical code path, since the catch clauses purge/reset state the
     * same way regardless of the Throwable's concrete type).
     */
    private static byte[] buildClassThatThrowsMidClinitBody() {
        ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_MAXS);
        cw.visit(Opcodes.V11,
                 Opcodes.ACC_PUBLIC | Opcodes.ACC_SUPER,
                 "au/net/zeus/jgdms/bae/test/Corrupted",
                 null, "java/lang/Object", null);
        MethodVisitor mv = cw.visitMethod(
                Opcodes.ACC_STATIC, "<clinit>", "()V", null, null);
        mv.visitCode();
        mv.visitMethodInsn(Opcodes.INVOKESTATIC,
                "java/lang/Thread", "sleep", "(J)V", false);
        mv.visitInsn(Opcodes.RETURN);
        mv.visitMaxs(2, 0);
        mv.visitEnd();
        cw.visitEnd();
        byte[] bytes = cw.toByteArray();

        for (int i = bytes.length - 1; i >= 0; i--) {
            if ((bytes[i] & 0xFF) == 0xB1) { // RETURN
                bytes[i] = (byte) 0xAA;      // TABLESWITCH
                return bytes;
            }
        }
        throw new IllegalStateException(
                "RETURN opcode not found in generated class — test fixture is broken");
    }

    /**
     * {@code indexClass} must fail secure when ASM throws partway through
     * parsing (after {@code visit()} already set the class name): it must
     * return {@code false}, reset {@code clinitOwner[0]} to {@code null}
     * (undoing what {@code visit()} set), and purge any {@code callGraph}/
     * {@code isNativeMap} entries it added for this class before the throw
     * (the {@code <clinit>} method's edge to {@code Thread.sleep} would
     * otherwise have already been recorded before the corrupted instruction
     * is reached).  A caller that only checked {@code clinitOwner[0] == null}
     * — as {@link JarAnalyzer} did before this fix — would previously have
     * seen a non-null owner and a (silently truncated) call graph, and
     * treated the class as cleanly, fully indexed.
     */
    @Test
    public void testIndexClass_ThrowableAfterVisit_FailsSecure() {
        byte[] corrupted = buildClassThatThrowsMidClinitBody();

        java.util.Map<String, java.util.Set<String>> callGraph =
                new java.util.HashMap<>();
        java.util.Map<String, Boolean> isNativeMap = new java.util.HashMap<>();
        String[] clinitOwner = { null };

        boolean indexed = ClinitBlockingVisitor.indexClass(
                corrupted, callGraph, isNativeMap, clinitOwner);

        assertFalse(indexed);
        assertNull(clinitOwner[0]);
        // No partial call-graph/native-method state may survive a failed parse.
        assertTrue(callGraph.isEmpty());
        assertTrue(isNativeMap.isEmpty());
    }

    /**
     * End-to-end: a JAR containing only the corrupted class from
     * {@link #buildClassThatThrowsMidClinitBody()} must not be reported
     * {@code CLEAN} / {@code SAFE} — it must receive the same fail-secure
     * verdict as any other unparseable class ({@code BLOCKING} +
     * {@code MISSING_CONSTRUCTOR}), proving the whole pipeline (not just
     * {@code indexClass} in isolation) routes the failure through the
     * existing parse-failure path.
     */
    @Test
    public void testJarAnalyzer_ThrowableMidClinitBody_NotReportedClean()
            throws Exception {
        byte[] corrupted = buildClassThatThrowsMidClinitBody();

        java.security.KeyPairGenerator kpg =
                java.security.KeyPairGenerator.getInstance("RSA");
        kpg.initialize(1024);
        JarAnalyzer analyzer = new JarAnalyzer(
                kpg.generateKeyPair().getPrivate(), "SHA256withRSA");

        java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
        try (java.util.jar.JarOutputStream jos =
                new java.util.jar.JarOutputStream(baos)) {
            java.util.jar.JarEntry entry = new java.util.jar.JarEntry(
                    "au/net/zeus/jgdms/bae/test/Corrupted.class");
            jos.putNextEntry(entry);
            jos.write(corrupted);
            jos.closeEntry();
        }

        au.net.zeus.jgdms.api.codebase.JarAnalysisReport report = analyzer.analyze(
                new au.net.zeus.jgdms.api.codebase.AnalysisRequest(
                        baos.toByteArray(), "irrelevant-hash", null));

        assertEquals(1, report.getResults().size());
        au.net.zeus.jgdms.api.codebase.ClassAnalysisResult car =
                report.getResults().values().iterator().next();
        assertEquals(ClinitVerdict.BLOCKING, car.getClinitVerdict());
        assertEquals(au.net.zeus.jgdms.api.codebase.AtomicSerialVerdict.MISSING_CONSTRUCTOR,
                car.getAtomicVerdict());
        assertEquals(au.net.zeus.jgdms.api.codebase.VerdictType.DANGEROUS,
                report.deriveVerdictType());
    }

    // -------------------------------------------------------------------------
    // BFS parent-pointer path reconstruction (Fix 4)
    // -------------------------------------------------------------------------

    /**
     * The parent-pointer rewrite of the BFS must reconstruct the exact same
     * root-to-sink path the old full-path-copy approach produced.  Chains
     * class A (reads a static field of B, triggering B's {@code <clinit>})
     * to class B (whose {@code <clinit>} calls the blocking sink directly),
     * and asserts {@code callPath} is exactly
     * {@code [A/<clinit>/()V, B/<clinit>/()V, java/lang/Thread/sleep/(J)V]}.
     */
    @Test
    public void testAnalyzeClinitReachability_PathReconstruction_MultiHop()
            throws Exception {
        String classA = "au/net/zeus/jgdms/bae/test/PathA";
        String classB = "au/net/zeus/jgdms/bae/test/PathB";

        byte[] aBytes = buildClinitReadingStaticField(classA, classB, "FLAG", "I");

        ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_FRAMES);
        cw.visit(Opcodes.V11,
                 Opcodes.ACC_PUBLIC | Opcodes.ACC_SUPER,
                 classB, null, "java/lang/Object", null);
        cw.visitField(Opcodes.ACC_PUBLIC | Opcodes.ACC_STATIC,
                "FLAG", "I", null, null).visitEnd();
        MethodVisitor mv = cw.visitMethod(
                Opcodes.ACC_STATIC, "<clinit>", "()V", null, null);
        mv.visitCode();
        mv.visitMethodInsn(Opcodes.INVOKESTATIC,
                "java/lang/Thread", "sleep", "(J)V", false);
        mv.visitInsn(Opcodes.RETURN);
        mv.visitMaxs(0, 0);
        mv.visitEnd();
        cw.visitEnd();
        byte[] bBytes = cw.toByteArray();

        java.util.Map<String, java.util.Set<String>> callGraph =
                new java.util.HashMap<>();
        java.util.Map<String, Boolean> isNativeMap = new java.util.HashMap<>();
        ClinitBlockingVisitor.indexClass(aBytes, callGraph, isNativeMap, new String[]{null});
        ClinitBlockingVisitor.indexClass(bBytes, callGraph, isNativeMap, new String[]{null});

        ClinitBlockingVisitor.ClinitAnalysisResult result =
                ClinitBlockingVisitor.analyzeClinitReachability(
                        classA, callGraph, isNativeMap, 20);

        assertEquals(ClinitVerdict.BLOCKING, result.verdict);
        java.util.List<String> expectedPath = java.util.Arrays.asList(
                classA + "/<clinit>/()V",
                classB + "/<clinit>/()V",
                "java/lang/Thread/sleep/(J)V");
        assertEquals(expectedPath, result.callPath);
    }

    /**
     * Depth-boundary regression (review requirement #2): a node reached
     * exactly AT {@code maxDepth} must still have its own callees checked
     * for a sink — it is only not <em>enqueued</em> for further expansion
     * beyond that.  Chains root A → B (depth 1) → C (depth 2), where C's
     * {@code <clinit>} calls the blocking sink directly (a depth-3 edge from
     * the root, but reachable purely by <em>checking</em> C's callees, not
     * by enqueuing past it).
     *
     * <p>With {@code maxDepth == 2}, C is processed (its callees ARE
     * checked) and the sink is found.  With {@code maxDepth == 1}, C is
     * discovered as B's callee (so it has a parent-pointer entry) but is
     * never enqueued/processed, so its callee — the sink — is never
     * reached, and the verdict must be {@code CLEAN}.  Getting the boundary
     * off by one either way would silently change the effective analysis
     * depth.
     */
    @Test
    public void testAnalyzeClinitReachability_DepthBoundary_CalleesOfMaxDepthNodeStillChecked()
            throws Exception {
        String classA = "au/net/zeus/jgdms/bae/test/DepthA";
        String classB = "au/net/zeus/jgdms/bae/test/DepthB";
        String classC = "au/net/zeus/jgdms/bae/test/DepthC";

        byte[] aBytes = buildClinitReadingStaticField(classA, classB, "FLAG", "I");
        byte[] bBytes = buildClassReadingStaticFieldAndDeclaring(classB, classC);

        ClassWriter cwC = new ClassWriter(ClassWriter.COMPUTE_FRAMES);
        cwC.visit(Opcodes.V11,
                  Opcodes.ACC_PUBLIC | Opcodes.ACC_SUPER,
                  classC, null, "java/lang/Object", null);
        MethodVisitor mvC = cwC.visitMethod(
                Opcodes.ACC_STATIC, "<clinit>", "()V", null, null);
        mvC.visitCode();
        mvC.visitMethodInsn(Opcodes.INVOKESTATIC,
                "java/lang/Thread", "sleep", "(J)V", false);
        mvC.visitInsn(Opcodes.RETURN);
        mvC.visitMaxs(0, 0);
        mvC.visitEnd();
        cwC.visitEnd();
        byte[] cBytes = cwC.toByteArray();

        java.util.Map<String, java.util.Set<String>> callGraph =
                new java.util.HashMap<>();
        java.util.Map<String, Boolean> isNativeMap = new java.util.HashMap<>();
        ClinitBlockingVisitor.indexClass(aBytes, callGraph, isNativeMap, new String[]{null});
        ClinitBlockingVisitor.indexClass(bBytes, callGraph, isNativeMap, new String[]{null});
        ClinitBlockingVisitor.indexClass(cBytes, callGraph, isNativeMap, new String[]{null});

        ClinitVerdict atMaxDepth = ClinitBlockingVisitor.analyzeClinitReachability(
                classA, callGraph, isNativeMap, 2).verdict;
        assertEquals(ClinitVerdict.BLOCKING, atMaxDepth);

        ClinitVerdict oneShallower = ClinitBlockingVisitor.analyzeClinitReachability(
                classA, callGraph, isNativeMap, 1).verdict;
        assertEquals(ClinitVerdict.CLEAN, oneShallower);
    }

    /**
     * Builds a class that both (a) declares its own static field {@code FLAG}
     * (of type {@code I}) — so that another class's {@code GETSTATIC} of
     * {@code className.FLAG} names a "real" declaring class — and (b) whose
     * {@code <clinit>} itself reads {@code fieldOwner.FLAG}, chaining onward
     * to {@code fieldOwner}'s {@code <clinit>}.
     */
    private static byte[] buildClassReadingStaticFieldAndDeclaring(
            String className, String fieldOwner) {
        ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_FRAMES);
        cw.visit(Opcodes.V11,
                 Opcodes.ACC_PUBLIC | Opcodes.ACC_SUPER,
                 className, null, "java/lang/Object", null);
        cw.visitField(Opcodes.ACC_PUBLIC | Opcodes.ACC_STATIC,
                "FLAG", "I", null, null).visitEnd();
        MethodVisitor mv = cw.visitMethod(
                Opcodes.ACC_STATIC, "<clinit>", "()V", null, null);
        mv.visitCode();
        mv.visitFieldInsn(Opcodes.GETSTATIC, fieldOwner, "FLAG", "I");
        mv.visitInsn(Opcodes.POP);
        mv.visitInsn(Opcodes.RETURN);
        mv.visitMaxs(0, 0);
        mv.visitEnd();
        cw.visitEnd();
        return cw.toByteArray();
    }

    // -------------------------------------------------------------------------
    // BlockingSinkRegistry.isPermissionGuard — unit checks
    // -------------------------------------------------------------------------

    @Test
    public void testIsPermissionGuard_SmCheckPermission_isTrue() {
        assertTrue(BlockingSinkRegistry.isPermissionGuard(
                "java/lang/SecurityManager", "checkPermission",
                "(Ljava/security/Permission;)V"));
    }

    @Test
    public void testIsPermissionGuard_SmCheckConnect_isTrue() {
        assertTrue(BlockingSinkRegistry.isPermissionGuard(
                "java/lang/SecurityManager", "checkConnect",
                "(Ljava/lang/String;I)V"));
    }

    @Test
    public void testIsPermissionGuard_SmCheckRead_isTrue() {
        assertTrue(BlockingSinkRegistry.isPermissionGuard(
                "java/lang/SecurityManager", "checkRead",
                "(Ljava/lang/String;)V"));
    }

    @Test
    public void testIsPermissionGuard_AcCheckPermission_isTrue() {
        assertTrue(BlockingSinkRegistry.isPermissionGuard(
                "java/security/AccessController", "checkPermission",
                "(Ljava/security/Permission;)V"));
    }

    @Test
    public void testIsPermissionGuard_DoPrivileged_isFalse() {
        assertFalse(BlockingSinkRegistry.isPermissionGuard(
                "java/security/AccessController", "doPrivileged",
                "(Ljava/security/PrivilegedAction;)Ljava/lang/Object;"));
    }

    @Test
    public void testIsPermissionGuard_ThreadSleep_isFalse() {
        assertFalse(BlockingSinkRegistry.isPermissionGuard(
                "java/lang/Thread", "sleep", "(J)V"));
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private static void assertTrue(boolean condition) {
        assertEquals(true, condition);
    }

    private static void assertFalse(boolean condition) {
        assertEquals(false, condition);
    }
}
