
#/*
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#*/

QA1NORM.dl       	= com.sun.jini.test.impl.norm.TestLease

QA1NORM_JARS            = qa1-norm-dl.jar

QAJARS     +=	$(QA1NORM_JARS)

qa1-norm-dl.jar: jartools
	rm -f $(QAJARSDIR)/$@
	@echo Creating $@
	@cd $(CLASSDIR); $(JAR) cf $(QAJARSDIR)/$@ -C $(JINICLASSES) com/sun/jini/proxy/BasicProxyTrustVerifier.class `$(QACLASSDEP) -in com.sun.jini.test com.sun.jini.test.impl.norm.LocalLease com.sun.jini.test.impl.norm.ConstrainableLocalLease com.sun.jini.test.impl.norm.DestructingLocalLease com.sun.jini.test.impl.norm.ConstrainableDestructingLocalLease com.sun.jini.test.impl.norm.FailingLocalLease com.sun.jini.test.impl.norm.ConstrainableFailingLocalLease com.sun.jini.test.impl.norm.TestLease com.sun.jini.test.impl.norm.ConstrainableTestLease com.sun.jini.test.share.AttrOne com.sun.jini.test.share.SunOfAttrOne com.sun.jini.test.share.AttrTwo com.sun.jini.test.impl.norm.LeaseBackEndImpl'$$'VerifierImpl com.sun.jini.test.impl.norm.LocalLease'$$'VerifierImpl $(subst $$,'$$',$(QA1NORM.impls:%=%_Stub)) $(subst $$,'$$',$(QA1NORM.dl))`
