
#/*
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#*/


QA_IO_MARSHALINPUTSTREAM_JARS = qa1-io-util-dl.jar \
				qa1-io-marshalinputstream-test.jar

QAJARS	+=	$(QA_IO_MARSHALINPUTSTREAM_JARS)

qa1-io-util-dl.jar: jartools
	rm -f $(QAJARSDIR)/$@
	@echo Creating $@
	@cd $(CLASSDIR); $(JAR) cf $(QAJARSDIR)/$@ \
		com/sun/jini/test/spec/io/util/FakeArgument.class \
		com/sun/jini/test/spec/io/util/FakeInterface.class

qa1-io-marshalinputstream-test.jar: jartools
	rm -f $(QAJARSDIR)/$@
	@echo Creating $@
	@cd $(CLASSDIR); $(JAR) cf $(QAJARSDIR)/$@ \
		-C $(MANIFESTDIR)/qa1-io-tests \
		META-INF/services/net.jini.security.IntegrityVerifier \
		com/sun/jini/test/spec/io/marshalinputstream/*.class
	@cd $(CLASSDIR); $(JAR) uf $(QAJARSDIR)/$@ `$(QACLASSDEP) \
		-in com.sun.jini.test \
		-out com.sun.jini.test.harness \
		-out com.sun.jini.test.spec.io.util.FakeArgument \
		-out com.sun.jini.test.spec.io.util.FakeInterface \
		-in net.jini \
		$(JSKPLATFORM.EXCLUDE) \
		com.sun.jini.test.spec.io.util.FakeIntegrityVerifier \
		com/sun/jini/test/spec/io/marshalinputstream`
