
#/*
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#*/


QA1MAHALO_JARS   = qa1-mahalo-dl.jar

QAJARS     +=	$(QA1MAHALO_JARS)

mahalo_jars: $(QA1MAHALO_JARS) qa1.jar

LOCAL_IMPLS = 

#qa1-mercury.jar: jartools
#	rm -f $(QAJARSDIR)/$@
#	@echo Create $@
#	@cd $(CLASSDIR); $(JAR) cf $(QAJARSDIR)/$@ `$(QACLASSDEP) -in com.sun.jini.test $(QA1MAHALO.impls) $(LOCAL_IMPLS) $(subst $$,'$$',$(QA1MAHALO.impls:%=%_Stub))`
#	@cd $(JINICLASSES); $(JAR) uf $(QAJARSDIR)/$@ `$(QACLASSDEP) -in com.sun.jini -in net.jini -hide com.sun.jini.test $(LOCAL_IMPLS) $(QA1MAHALO.impls) $(subst $$,'$$',$(QA1MAHALO.impls:%=%_Stub))`

qa1-mahalo-dl.jar: jartools
	rm -f $(QAJARSDIR)/$@
	@echo Create $@
	@cd $(CLASSDIR); $(JAR) cf $(QAJARSDIR)/$@ -C $(JINICLASSES)  net/jini/lookup/entry/Name.class `$(QACLASSDEP) -in com.sun.jini.test $(subst $$,'$$',$(QA1MAHALO.impls:%=%_Stub))`
