testClass=org.apache.river.test.spec.jeri.transport.NullPointerExceptionTest
testCategories=jeri,jeri_spec
testConfiguration=<url: HttpsServerEndpointTest.config>
org.apache.river.qa.harness.runkitserver=false 
org.apache.river.qa.harness.runjiniserver=false
org.apache.river.qa.harness.verifier=${org.apache.river.qa.harness.verifier} org.apache.river.qa.harness.SkipConfigTestVerifier
org.apache.river.qa.harness.skipConfigs=none,jeri,jrmp,kerberos,http