testClass=SecurityExceptionConstructor
testCategories=policyprovider,policyprovider_spec
testPolicyfile=policyProviderNoAccessClass.policy
org.apache.river.qa.harness.runkitserver=false 
org.apache.river.qa.harness.runjiniserver=false
org.apache.river.qa.harness.securityproperties=<url: securityexceptionconstructornoaccessclass.properties>
#org.apache.river.qa.harness.securityproperties=<url: ../securityprovider.properties>
