
#/*
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#*/

# Individual classes that need to be placed in the downloadable jar file

SDM.impls  =	net.jini.lookup.ServiceDiscoveryManager$$LookupCacheImpl$$LookupListener

QASDM.dl	= com.sun.jini.test.spec.servicediscovery.AbstractBaseTest$$TestService \
                  com.sun.jini.test.spec.servicediscovery.AbstractBaseTest$$TestServiceIntAttr \
                  net.jini.lookup.entry.Name

QASDM_JARS = qa1-servicediscovery-dl.jar

QAJARS     +=	$(QASDM_JARS)

qa1-servicediscovery-dl.jar: jartools
	rm -f $(QAJARSDIR)/$@
	@echo Creating $@
	@cd $(CLASSDIR); $(JAR) cf $(QAJARSDIR)/$@ -C $(MANIFESTDIR)/servicediscovery-dl META-INF/PREFERRED.LIST `$(QACLASSDEP) -in net.jini.lookup -in com.sun.jini.test -hide net.jini.lookup $(subst $$,'$$',$(SDM.impls:%=%_Stub)) $(subst $$,'$$',$(QASDM.impls:%=%_Stub)) $(subst $$,'$$',$(QASDM.dl))`
	@cd $(JINICLASSES); $(JAR) uf $(QAJARSDIR)/$@ `$(QACLASSDEP) -in net.jini.lookup -in com.sun.jini -in com.sun.jini.test com.sun.jini.proxy.BasicProxyTrustVerifier -show net.jini.lookup -show com.sun.jini.proxy $(subst $$,'$$',$(SDM.impls:%=%_Stub)) $(subst $$,'$$',$(QASDM.impls:%=%_Stub)) $(subst $$,'$$',$(QASDM.dl))`
