testClass=DoPrivilegedExceptionTest
testCategories=security,security_spec
testClasspath=<file:lib/qa1-securityDoPrivileged.jar>$:<file:lib/qa1-securityUtil.jar>$:<harnessJar>$:<testJar>$:${com.sun.jini.jsk.home}$/lib$/jsk-platform.jar$:${com.sun.jini.jsk.home}$/lib$/jsk-lib.jar
testPolicyfile=security.policy
com.sun.jini.qa.harness.runkitserver=false 
com.sun.jini.qa.harness.runjiniserver=false
testOverrideProviders=
