testClass=ComputeDigestCodebase
testCategories=url_spec,url

# Number of ComputeDigestCodebase Test Cases
ComputeDigestCodebase.testCases.1=42
ComputeDigestCodebase.testCases.2=42
ComputeDigestCodebase.testCases.3=27
ComputeDigestCodebase.testCases.4=27
ComputeDigestCodebase.testCases.5=14
ComputeDigestCodebase.testCases.6=4
ComputeDigestCodebase.testCases.7=2
ComputeDigestCodebase.testCases.8=16
ComputeDigestCodebase.testCases.9=1
ComputeDigestCodebase.testCases.10=1
ComputeDigestCodebase.testCases.11=1


#        ComputeDigestCodebase.1.* Tests
ComputeDigestCodebase.SrcDir.1=${com.sun.jini.test.home}$/lib
ComputeDigestCodebase.SrcDir.1.1=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.2=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.3=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.4=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.5=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.6=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.7=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.8=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.9=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.10=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.11=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.12=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.13=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.14=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.15=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.16=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.17=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.18=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.19=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.20=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.21=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.22=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.23=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.24=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.25=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.26=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.27=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.28=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.29=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.30=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.31=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.32=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.33=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.34=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.35=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.36=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.37=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.38=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.39=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.40=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.41=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.SrcDir.1.42=${ComputeDigestCodebase.SrcDir.1}
ComputeDigestCodebase.CodeBase.1.1=httpmd:/qa1-httpmd.jar;MD5=AAAAA
ComputeDigestCodebase.CodeBase.1.2=httpmd:/qa1-httpmd.jar;MD5=AAAAA,comments
ComputeDigestCodebase.CodeBase.1.3=httpmd:/qa1-httpmd.jar;md5=AAAAA
ComputeDigestCodebase.CodeBase.1.4=httpmd:/qa1-httpmd.jar;md5=AAAAA,comments
ComputeDigestCodebase.CodeBase.1.5=httpmd:/qa1-httpmd.jar;SHA=AAAAA
ComputeDigestCodebase.CodeBase.1.6=httpmd:/qa1-httpmd.jar;SHA=AAAAA,comments
ComputeDigestCodebase.CodeBase.1.7=httpmd:/qa1-httpmd.jar;sha=AAAAA
ComputeDigestCodebase.CodeBase.1.8=httpmd:/qa1-httpmd.jar;sha=AAAAA,comments
ComputeDigestCodebase.CodeBase.1.9=httpmd:/qa1-httpmd.jar;MD5=AAAAA?query=qqq
ComputeDigestCodebase.CodeBase.1.10=httpmd:/qa1-httpmd.jar;MD5=AAAAA,comments?query=qqq
ComputeDigestCodebase.CodeBase.1.11=httpmd:/qa1-httpmd.jar;md5=AAAAA?query=qqq
ComputeDigestCodebase.CodeBase.1.12=httpmd:/qa1-httpmd.jar;md5=AAAAA,comments?query=qqq
ComputeDigestCodebase.CodeBase.1.13=httpmd:/qa1-httpmd.jar;SHA=AAAAA?query=qqq
ComputeDigestCodebase.CodeBase.1.14=httpmd:/qa1-httpmd.jar;SHA=AAAAA,comments?query=qqq
ComputeDigestCodebase.CodeBase.1.15=httpmd:/qa1-httpmd.jar;sha=AAAAA?query=qqq
ComputeDigestCodebase.CodeBase.1.16=httpmd:/qa1-httpmd.jar;sha=AAAAA,comments?query=qqq
#ComputeDigestCodebase.CodeBase.1.17=httpmd:/qa1-httpmd.jar;MD5=AAAAA#Ref
ComputeDigestCodebase.CodeBase.1.17=httpmd:/qa1-httpmd.jar;MD5=AAAAA<PoundSign>Ref
#ComputeDigestCodebase.CodeBase.1.18=httpmd:/qa1-httpmd.jar;MD5=AAAAA,comments#Ref
ComputeDigestCodebase.CodeBase.1.18=httpmd:/qa1-httpmd.jar;MD5=AAAAA,comments<PoundSign>Ref
#ComputeDigestCodebase.CodeBase.1.19=httpmd:/qa1-httpmd.jar;md5=AAAAA#Ref
ComputeDigestCodebase.CodeBase.1.19=httpmd:/qa1-httpmd.jar;md5=AAAAA<PoundSign>Ref
#ComputeDigestCodebase.CodeBase.1.20=httpmd:/qa1-httpmd.jar;md5=AAAAA,comments#Ref
ComputeDigestCodebase.CodeBase.1.20=httpmd:/qa1-httpmd.jar;md5=AAAAA,comments<PoundSign>Ref
#ComputeDigestCodebase.CodeBase.1.21=httpmd:/qa1-httpmd.jar;SHA=AAAAA#Ref
ComputeDigestCodebase.CodeBase.1.21=httpmd:/qa1-httpmd.jar;SHA=AAAAA<PoundSign>Ref
#ComputeDigestCodebase.CodeBase.1.22=httpmd:/qa1-httpmd.jar;SHA=AAAAA,comments#Ref
ComputeDigestCodebase.CodeBase.1.22=httpmd:/qa1-httpmd.jar;SHA=AAAAA,comments<PoundSign>Ref
#ComputeDigestCodebase.CodeBase.1.23=httpmd:/qa1-httpmd.jar;sha=AAAAA#Ref
ComputeDigestCodebase.CodeBase.1.23=httpmd:/qa1-httpmd.jar;sha=AAAAA<PoundSign>Ref
#ComputeDigestCodebase.CodeBase.1.24=httpmd:/qa1-httpmd.jar;sha=AAAAA,comments#Ref
ComputeDigestCodebase.CodeBase.1.24=httpmd:/qa1-httpmd.jar;sha=AAAAA,comments<PoundSign>Ref
ComputeDigestCodebase.CodeBase.1.25=httpmd:/qa1-httpmd.jar;md5=AAAAA httpmd:/qa1-httpmd-another.jar;md5=AAAAA
ComputeDigestCodebase.CodeBase.1.26=httpmd:/qa1-httpmd.jar;md5=AAAAA,comments httpmd:/qa1-httpmd-another.jar;md5=AAAAA
ComputeDigestCodebase.CodeBase.1.27=httpmd://localhost/qa1-httpmd.jar;MD5=AAAAA
ComputeDigestCodebase.CodeBase.1.28=httpmd://localhost:1111/qa1-httpmd.jar;MD5=AAAAA
ComputeDigestCodebase.CodeBase.1.29=httpmd://localhost/qa1-httpmd.jar;MD5=AAAAA,comments
ComputeDigestCodebase.CodeBase.1.30=httpmd://localhost:1111/qa1-httpmd.jar;MD5=AAAAA,comments
ComputeDigestCodebase.CodeBase.1.31=httpmd://localhost/qa1-httpmd.jar;MD5=AAAAA?query=qqq
ComputeDigestCodebase.CodeBase.1.32=httpmd://localhost:1111/qa1-httpmd.jar;MD5=AAAAA?query=qqq
ComputeDigestCodebase.CodeBase.1.33=httpmd://localhost/qa1-httpmd.jar;MD5=AAAAA,comments?query=qqq
ComputeDigestCodebase.CodeBase.1.34=httpmd://localhost:1111/qa1-httpmd.jar;MD5=AAAAA,comments?query=qqq
#ComputeDigestCodebase.CodeBase.1.35=httpmd://localhost/qa1-httpmd.jar;MD5=AAAAA#Ref
ComputeDigestCodebase.CodeBase.1.35=httpmd://localhost/qa1-httpmd.jar;MD5=AAAAA<PoundSign>Ref
#ComputeDigestCodebase.CodeBase.1.36=httpmd://localhost:1111/qa1-httpmd.jar;MD5=AAAAA#Ref
ComputeDigestCodebase.CodeBase.1.36=httpmd://localhost:1111/qa1-httpmd.jar;MD5=AAAAA<PoundSign>Ref
#ComputeDigestCodebase.CodeBase.1.37=httpmd://localhost/qa1-httpmd.jar;MD5=AAAAA,comments#Ref
ComputeDigestCodebase.CodeBase.1.37=httpmd://localhost/qa1-httpmd.jar;MD5=AAAAA,comments<PoundSign>Ref
#ComputeDigestCodebase.CodeBase.1.38=httpmd://localhost:1111/qa1-httpmd.jar;MD5=AAAAA,comments#Ref
ComputeDigestCodebase.CodeBase.1.38=httpmd://localhost:1111/qa1-httpmd.jar;MD5=AAAAA,comments<PoundSign>Ref
ComputeDigestCodebase.CodeBase.1.39=httpmd://localhost/qa1-httpmd.jar;md5=AAAAA httpmd:/qa1-httpmd-another.jar;md5=AAAAA
ComputeDigestCodebase.CodeBase.1.40=httpmd://localhost:1111/qa1-httpmd.jar;md5=AAAAA httpmd:/qa1-httpmd-another.jar;md5=AAAAA
ComputeDigestCodebase.CodeBase.1.41=httpmd://localhost/qa1-httpmd.jar;md5=AAAAA,comments httpmd:/qa1-httpmd-another.jar;md5=AAAAA
ComputeDigestCodebase.CodeBase.1.42=httpmd://localhost:1111/qa1-httpmd.jar;md5=AAAAA,comments httpmd:/qa1-httpmd-another.jar;md5=AAAAA


#        ComputeDigestCodebase.2.* Tests
ComputeDigestCodebase.SrcDir.2=${java.io.tmpdir}
ComputeDigestCodebase.SrcDir.2.1=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.2=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.3=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.4=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.5=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.6=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.7=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.8=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.9=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.10=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.11=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.12=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.13=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.14=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.15=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.16=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.17=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.18=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.19=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.20=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.21=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.22=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.23=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.24=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.25=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.26=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.27=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.28=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.29=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.30=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.31=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.32=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.33=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.34=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.35=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.36=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.37=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.38=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.39=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.40=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.41=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.SrcDir.2.42=${ComputeDigestCodebase.SrcDir.2}
ComputeDigestCodebase.CodeBase.2.1=httpmd:/empty_file;MD5=AAAAA
ComputeDigestCodebase.CodeBase.2.2=httpmd:/empty_file;MD5=AAAAA,comments
ComputeDigestCodebase.CodeBase.2.3=httpmd:/empty_file;md5=AAAAA
ComputeDigestCodebase.CodeBase.2.4=httpmd:/empty_file;md5=AAAAA,comments
ComputeDigestCodebase.CodeBase.2.5=httpmd:/empty_file;SHA=AAAAA
ComputeDigestCodebase.CodeBase.2.6=httpmd:/empty_file;SHA=AAAAA,comments
ComputeDigestCodebase.CodeBase.2.7=httpmd:/empty_file;sha=AAAAA
ComputeDigestCodebase.CodeBase.2.8=httpmd:/empty_file;sha=AAAAA,comments
ComputeDigestCodebase.CodeBase.2.9=httpmd:/empty_file;MD5=AAAAA?query=qqq
ComputeDigestCodebase.CodeBase.2.10=httpmd:/empty_file;MD5=AAAAA,comments?query=qqq
ComputeDigestCodebase.CodeBase.2.11=httpmd:/empty_file;md5=AAAAA?query=qqq
ComputeDigestCodebase.CodeBase.2.12=httpmd:/empty_file;md5=AAAAA,comments?query=qqq
ComputeDigestCodebase.CodeBase.2.13=httpmd:/empty_file;SHA=AAAAA?query=qqq
ComputeDigestCodebase.CodeBase.2.14=httpmd:/empty_file;SHA=AAAAA,comments?query=qqq
ComputeDigestCodebase.CodeBase.2.15=httpmd:/empty_file;sha=AAAAA?query=qqq
ComputeDigestCodebase.CodeBase.2.16=httpmd:/empty_file;sha=AAAAA,comments?query=qqq
#ComputeDigestCodebase.CodeBase.2.17=httpmd:/empty_file;MD5=AAAAA#Ref
ComputeDigestCodebase.CodeBase.2.17=httpmd:/empty_file;MD5=AAAAA<PoundSign>Ref
#ComputeDigestCodebase.CodeBase.2.18=httpmd:/empty_file;MD5=AAAAA,comments#Ref
ComputeDigestCodebase.CodeBase.2.18=httpmd:/empty_file;MD5=AAAAA,comments<PoundSign>Ref
#ComputeDigestCodebase.CodeBase.2.19=httpmd:/empty_file;md5=AAAAA#Ref
ComputeDigestCodebase.CodeBase.2.19=httpmd:/empty_file;md5=AAAAA<PoundSign>Ref
#ComputeDigestCodebase.CodeBase.2.20=httpmd:/empty_file;md5=AAAAA,comments#Ref
ComputeDigestCodebase.CodeBase.2.20=httpmd:/empty_file;md5=AAAAA,comments<PoundSign>Ref
#ComputeDigestCodebase.CodeBase.2.21=httpmd:/empty_file;SHA=AAAAA#Ref
ComputeDigestCodebase.CodeBase.2.21=httpmd:/empty_file;SHA=AAAAA<PoundSign>Ref
#ComputeDigestCodebase.CodeBase.2.22=httpmd:/empty_file;SHA=AAAAA,comments#Ref
ComputeDigestCodebase.CodeBase.2.22=httpmd:/empty_file;SHA=AAAAA,comments<PoundSign>Ref
#ComputeDigestCodebase.CodeBase.2.23=httpmd:/empty_file;sha=AAAAA#Ref
ComputeDigestCodebase.CodeBase.2.23=httpmd:/empty_file;sha=AAAAA<PoundSign>Ref
#ComputeDigestCodebase.CodeBase.2.24=httpmd:/empty_file;sha=AAAAA,comments#Ref
ComputeDigestCodebase.CodeBase.2.24=httpmd:/empty_file;sha=AAAAA,comments<PoundSign>Ref
ComputeDigestCodebase.CodeBase.2.25=httpmd:/empty_file;md5=AAAAA httpmd:/empty_file;md5=AAAAA
ComputeDigestCodebase.CodeBase.2.26=httpmd:/empty_file;md5=AAAAA,comments httpmd:/empty_file;md5=AAAAA
ComputeDigestCodebase.CodeBase.2.27=httpmd://localhost/empty_file;MD5=AAAAA
ComputeDigestCodebase.CodeBase.2.28=httpmd://localhost:1111/empty_file;MD5=AAAAA
ComputeDigestCodebase.CodeBase.2.29=httpmd://localhost/empty_file;MD5=AAAAA,comments
ComputeDigestCodebase.CodeBase.2.30=httpmd://localhost:1111/empty_file;MD5=AAAAA,comments
ComputeDigestCodebase.CodeBase.2.31=httpmd://localhost/empty_file;MD5=AAAAA?query=qqq
ComputeDigestCodebase.CodeBase.2.32=httpmd://localhost:1111/empty_file;MD5=AAAAA?query=qqq
ComputeDigestCodebase.CodeBase.2.33=httpmd://localhost/empty_file;MD5=AAAAA,comments?query=qqq
ComputeDigestCodebase.CodeBase.2.34=httpmd://localhost:1111/empty_file;MD5=AAAAA,comments?query=qqq
#ComputeDigestCodebase.CodeBase.2.35=httpmd://localhost/empty_file;MD5=AAAAA#Ref
ComputeDigestCodebase.CodeBase.2.35=httpmd://localhost/empty_file;MD5=AAAAA<PoundSign>Ref
#ComputeDigestCodebase.CodeBase.2.36=httpmd://localhost:1111/empty_file;MD5=AAAAA#Ref
ComputeDigestCodebase.CodeBase.2.36=httpmd://localhost:1111/empty_file;MD5=AAAAA<PoundSign>Ref
#ComputeDigestCodebase.CodeBase.2.37=httpmd://localhost/empty_file;MD5=AAAAA,comments#Ref
ComputeDigestCodebase.CodeBase.2.37=httpmd://localhost/empty_file;MD5=AAAAA,comments<PoundSign>Ref
#ComputeDigestCodebase.CodeBase.2.38=httpmd://localhost:1111/empty_file;MD5=AAAAA,comments#Ref
ComputeDigestCodebase.CodeBase.2.38=httpmd://localhost:1111/empty_file;MD5=AAAAA,comments<PoundSign>Ref
ComputeDigestCodebase.CodeBase.2.39=httpmd://localhost/empty_file;md5=AAAAA httpmd:/empty_file;md5=AAAAA
ComputeDigestCodebase.CodeBase.2.40=httpmd://localhost:1111/empty_file;md5=AAAAA httpmd:/empty_file;md5=AAAAA
ComputeDigestCodebase.CodeBase.2.41=httpmd://localhost/empty_file;md5=AAAAA,comments httpmd:/empty_file;md5=AAAAA
ComputeDigestCodebase.CodeBase.2.42=httpmd://localhost:1111/empty_file;md5=AAAAA,comments httpmd:/empty_file;md5=AAAAA


#        ComputeDigestCodebase.3.* Tests
ComputeDigestCodebase.SrcDir.3=${com.sun.jini.test.home}$/lib
ComputeDigestCodebase.SrcDir.3.1=${ComputeDigestCodebase.SrcDir.3}
ComputeDigestCodebase.SrcDir.3.2=${ComputeDigestCodebase.SrcDir.3}
ComputeDigestCodebase.SrcDir.3.3=${ComputeDigestCodebase.SrcDir.3}
ComputeDigestCodebase.SrcDir.3.4=${ComputeDigestCodebase.SrcDir.3}
ComputeDigestCodebase.SrcDir.3.5=${ComputeDigestCodebase.SrcDir.3}
ComputeDigestCodebase.SrcDir.3.6=${ComputeDigestCodebase.SrcDir.3}
ComputeDigestCodebase.SrcDir.3.7=${ComputeDigestCodebase.SrcDir.3}
ComputeDigestCodebase.SrcDir.3.8=${ComputeDigestCodebase.SrcDir.3}
ComputeDigestCodebase.SrcDir.3.9=${ComputeDigestCodebase.SrcDir.3}
ComputeDigestCodebase.SrcDir.3.10=${ComputeDigestCodebase.SrcDir.3}
ComputeDigestCodebase.SrcDir.3.11=${ComputeDigestCodebase.SrcDir.3}
ComputeDigestCodebase.SrcDir.3.12=${ComputeDigestCodebase.SrcDir.3}
ComputeDigestCodebase.SrcDir.3.13=${ComputeDigestCodebase.SrcDir.3}
ComputeDigestCodebase.SrcDir.3.14=${ComputeDigestCodebase.SrcDir.3}
ComputeDigestCodebase.SrcDir.3.15=${ComputeDigestCodebase.SrcDir.3}
ComputeDigestCodebase.SrcDir.3.16=${ComputeDigestCodebase.SrcDir.3}
ComputeDigestCodebase.SrcDir.3.17=${ComputeDigestCodebase.SrcDir.3}
ComputeDigestCodebase.SrcDir.3.18=${ComputeDigestCodebase.SrcDir.3}
ComputeDigestCodebase.SrcDir.3.19=${ComputeDigestCodebase.SrcDir.3}
ComputeDigestCodebase.SrcDir.3.20=${ComputeDigestCodebase.SrcDir.3}
ComputeDigestCodebase.SrcDir.3.21=${ComputeDigestCodebase.SrcDir.3}
ComputeDigestCodebase.SrcDir.3.22=${ComputeDigestCodebase.SrcDir.3}
ComputeDigestCodebase.SrcDir.3.23=${ComputeDigestCodebase.SrcDir.3}
ComputeDigestCodebase.SrcDir.3.24=${ComputeDigestCodebase.SrcDir.3}
ComputeDigestCodebase.SrcDir.3.25=${ComputeDigestCodebase.SrcDir.3}
ComputeDigestCodebase.SrcDir.3.26=${ComputeDigestCodebase.SrcDir.3}
ComputeDigestCodebase.SrcDir.3.27=${ComputeDigestCodebase.SrcDir.3}
ComputeDigestCodebase.CodeBase.3.1=httpmd:qa1-httpmd.jar;MD5=AAAAA
ComputeDigestCodebase.CodeBase.3.2=httpmd:qa1-httpmd.jar;MD5=AAAAA,comments
ComputeDigestCodebase.CodeBase.3.3=httpmd:qa1-httpmd.jar;md5=AAAAA
ComputeDigestCodebase.CodeBase.3.4=httpmd:qa1-httpmd.jar;md5=AAAAA,comments
ComputeDigestCodebase.CodeBase.3.5=httpmd:qa1-httpmd.jar;SHA=AAAAA
ComputeDigestCodebase.CodeBase.3.6=httpmd:qa1-httpmd.jar;SHA=AAAAA,comments
ComputeDigestCodebase.CodeBase.3.7=httpmd:qa1-httpmd.jar;sha=AAAAA
ComputeDigestCodebase.CodeBase.3.8=httpmd:qa1-httpmd.jar;sha=AAAAA,comments
ComputeDigestCodebase.CodeBase.3.9=httpmd:qa1-httpmd.jar;MD5=AAAAA?query=qqq
ComputeDigestCodebase.CodeBase.3.10=httpmd:qa1-httpmd.jar;MD5=AAAAA,comments?query=qqq
ComputeDigestCodebase.CodeBase.3.11=httpmd:qa1-httpmd.jar;md5=AAAAA?query=qqq
ComputeDigestCodebase.CodeBase.3.12=httpmd:qa1-httpmd.jar;md5=AAAAA,comments?query=qqq
ComputeDigestCodebase.CodeBase.3.13=httpmd:qa1-httpmd.jar;SHA=AAAAA?query=qqq
ComputeDigestCodebase.CodeBase.3.14=httpmd:qa1-httpmd.jar;SHA=AAAAA,comments?query=qqq
ComputeDigestCodebase.CodeBase.3.15=httpmd:qa1-httpmd.jar;sha=AAAAA?query=qqq
ComputeDigestCodebase.CodeBase.3.16=httpmd:qa1-httpmd.jar;sha=AAAAA,comments?query=qqq
#ComputeDigestCodebase.CodeBase.3.17=httpmd:qa1-httpmd.jar;MD5=AAAAA#Ref
ComputeDigestCodebase.CodeBase.3.17=httpmd:qa1-httpmd.jar;MD5=AAAAA<PoundSign>Ref
#ComputeDigestCodebase.CodeBase.3.18=httpmd:qa1-httpmd.jar;MD5=AAAAA,comments#Ref
ComputeDigestCodebase.CodeBase.3.18=httpmd:qa1-httpmd.jar;MD5=AAAAA,comments<PoundSign>Ref
#ComputeDigestCodebase.CodeBase.3.19=httpmd:qa1-httpmd.jar;md5=AAAAA#Ref
ComputeDigestCodebase.CodeBase.3.19=httpmd:qa1-httpmd.jar;md5=AAAAA<PoundSign>Ref
#ComputeDigestCodebase.CodeBase.3.20=httpmd:qa1-httpmd.jar;md5=AAAAA,comments#Ref
ComputeDigestCodebase.CodeBase.3.20=httpmd:qa1-httpmd.jar;md5=AAAAA,comments<PoundSign>Ref
#ComputeDigestCodebase.CodeBase.3.21=httpmd:qa1-httpmd.jar;SHA=AAAAA#Ref
ComputeDigestCodebase.CodeBase.3.21=httpmd:qa1-httpmd.jar;SHA=AAAAA<PoundSign>Ref
#ComputeDigestCodebase.CodeBase.3.22=httpmd:qa1-httpmd.jar;SHA=AAAAA,comments#Ref
ComputeDigestCodebase.CodeBase.3.22=httpmd:qa1-httpmd.jar;SHA=AAAAA,comments<PoundSign>Ref
#ComputeDigestCodebase.CodeBase.3.23=httpmd:qa1-httpmd.jar;sha=AAAAA#Ref
ComputeDigestCodebase.CodeBase.3.23=httpmd:qa1-httpmd.jar;sha=AAAAA<PoundSign>Ref
#ComputeDigestCodebase.CodeBase.3.24=httpmd:qa1-httpmd.jar;sha=AAAAA,comments#Ref
ComputeDigestCodebase.CodeBase.3.24=httpmd:qa1-httpmd.jar;sha=AAAAA,comments<PoundSign>Ref
ComputeDigestCodebase.CodeBase.3.25=httpmd:qa1-httpmd.jar;md5=AAAAA httpmd:qa1-httpmd-another.jar;md5=AAAAA
ComputeDigestCodebase.CodeBase.3.26=httpmd:qa1-httpmd.jar;md5=AAAAA,comments httpmd:qa1-httpmd-another.jar;md5=AAAAA
ComputeDigestCodebase.CodeBase.3.27=httpmd:qa1-httpmd.jar;md5=AAAAA,comments httpmd:/qa1-httpmd-another.jar;md5=AAAAA


#        ComputeDigestCodebase.4.* Tests
ComputeDigestCodebase.SrcDir.4=${java.io.tmpdir}
ComputeDigestCodebase.SrcDir.4.1=${ComputeDigestCodebase.SrcDir.4}
ComputeDigestCodebase.SrcDir.4.2=${ComputeDigestCodebase.SrcDir.4}
ComputeDigestCodebase.SrcDir.4.3=${ComputeDigestCodebase.SrcDir.4}
ComputeDigestCodebase.SrcDir.4.4=${ComputeDigestCodebase.SrcDir.4}
ComputeDigestCodebase.SrcDir.4.5=${ComputeDigestCodebase.SrcDir.4}
ComputeDigestCodebase.SrcDir.4.6=${ComputeDigestCodebase.SrcDir.4}
ComputeDigestCodebase.SrcDir.4.7=${ComputeDigestCodebase.SrcDir.4}
ComputeDigestCodebase.SrcDir.4.8=${ComputeDigestCodebase.SrcDir.4}
ComputeDigestCodebase.SrcDir.4.9=${ComputeDigestCodebase.SrcDir.4}
ComputeDigestCodebase.SrcDir.4.10=${ComputeDigestCodebase.SrcDir.4}
ComputeDigestCodebase.SrcDir.4.11=${ComputeDigestCodebase.SrcDir.4}
ComputeDigestCodebase.SrcDir.4.12=${ComputeDigestCodebase.SrcDir.4}
ComputeDigestCodebase.SrcDir.4.13=${ComputeDigestCodebase.SrcDir.4}
ComputeDigestCodebase.SrcDir.4.14=${ComputeDigestCodebase.SrcDir.4}
ComputeDigestCodebase.SrcDir.4.15=${ComputeDigestCodebase.SrcDir.4}
ComputeDigestCodebase.SrcDir.4.16=${ComputeDigestCodebase.SrcDir.4}
ComputeDigestCodebase.SrcDir.4.17=${ComputeDigestCodebase.SrcDir.4}
ComputeDigestCodebase.SrcDir.4.18=${ComputeDigestCodebase.SrcDir.4}
ComputeDigestCodebase.SrcDir.4.19=${ComputeDigestCodebase.SrcDir.4}
ComputeDigestCodebase.SrcDir.4.20=${ComputeDigestCodebase.SrcDir.4}
ComputeDigestCodebase.SrcDir.4.21=${ComputeDigestCodebase.SrcDir.4}
ComputeDigestCodebase.SrcDir.4.22=${ComputeDigestCodebase.SrcDir.4}
ComputeDigestCodebase.SrcDir.4.23=${ComputeDigestCodebase.SrcDir.4}
ComputeDigestCodebase.SrcDir.4.24=${ComputeDigestCodebase.SrcDir.4}
ComputeDigestCodebase.SrcDir.4.25=${ComputeDigestCodebase.SrcDir.4}
ComputeDigestCodebase.SrcDir.4.26=${ComputeDigestCodebase.SrcDir.4}
ComputeDigestCodebase.SrcDir.4.27=${ComputeDigestCodebase.SrcDir.4}
ComputeDigestCodebase.CodeBase.4.1=httpmd:empty_file;MD5=AAAAA
ComputeDigestCodebase.CodeBase.4.2=httpmd:empty_file;MD5=AAAAA,comments
ComputeDigestCodebase.CodeBase.4.3=httpmd:empty_file;md5=AAAAA
ComputeDigestCodebase.CodeBase.4.4=httpmd:empty_file;md5=AAAAA,comments
ComputeDigestCodebase.CodeBase.4.5=httpmd:empty_file;SHA=AAAAA
ComputeDigestCodebase.CodeBase.4.6=httpmd:empty_file;SHA=AAAAA,comments
ComputeDigestCodebase.CodeBase.4.7=httpmd:empty_file;sha=AAAAA
ComputeDigestCodebase.CodeBase.4.8=httpmd:empty_file;sha=AAAAA,comments
ComputeDigestCodebase.CodeBase.4.9=httpmd:empty_file;MD5=AAAAA?query=qqq
ComputeDigestCodebase.CodeBase.4.10=httpmd:empty_file;MD5=AAAAA,comments?query=qqq
ComputeDigestCodebase.CodeBase.4.11=httpmd:empty_file;md5=AAAAA?query=qqq
ComputeDigestCodebase.CodeBase.4.12=httpmd:empty_file;md5=AAAAA,comments?query=qqq
ComputeDigestCodebase.CodeBase.4.13=httpmd:empty_file;SHA=AAAAA?query=qqq
ComputeDigestCodebase.CodeBase.4.14=httpmd:empty_file;SHA=AAAAA,comments?query=qqq
ComputeDigestCodebase.CodeBase.4.15=httpmd:empty_file;sha=AAAAA?query=qqq
ComputeDigestCodebase.CodeBase.4.16=httpmd:empty_file;sha=AAAAA,comments?query=qqq
#ComputeDigestCodebase.CodeBase.4.17=httpmd:empty_file;MD5=AAAAA#Ref
ComputeDigestCodebase.CodeBase.4.17=httpmd:empty_file;MD5=AAAAA<PoundSign>Ref
#ComputeDigestCodebase.CodeBase.4.18=httpmd:empty_file;MD5=AAAAA,comments#Ref
ComputeDigestCodebase.CodeBase.4.18=httpmd:empty_file;MD5=AAAAA,comments<PoundSign>Ref
#ComputeDigestCodebase.CodeBase.4.19=httpmd:empty_file;md5=AAAAA#Ref
ComputeDigestCodebase.CodeBase.4.19=httpmd:empty_file;md5=AAAAA<PoundSign>Ref
#ComputeDigestCodebase.CodeBase.4.20=httpmd:empty_file;md5=AAAAA,comments#Ref
ComputeDigestCodebase.CodeBase.4.20=httpmd:empty_file;md5=AAAAA,comments<PoundSign>Ref
#ComputeDigestCodebase.CodeBase.4.21=httpmd:empty_file;SHA=AAAAA#Ref
ComputeDigestCodebase.CodeBase.4.21=httpmd:empty_file;SHA=AAAAA<PoundSign>Ref
#ComputeDigestCodebase.CodeBase.4.22=httpmd:empty_file;SHA=AAAAA,comments#Ref
ComputeDigestCodebase.CodeBase.4.22=httpmd:empty_file;SHA=AAAAA,comments<PoundSign>Ref
#ComputeDigestCodebase.CodeBase.4.23=httpmd:empty_file;sha=AAAAA#Ref
ComputeDigestCodebase.CodeBase.4.23=httpmd:empty_file;sha=AAAAA<PoundSign>Ref
#ComputeDigestCodebase.CodeBase.4.24=httpmd:empty_file;sha=AAAAA,comments#Ref
ComputeDigestCodebase.CodeBase.4.24=httpmd:empty_file;sha=AAAAA,comments<PoundSign>Ref
ComputeDigestCodebase.CodeBase.4.25=httpmd:empty_file;md5=AAAAA httpmd:empty_file;md5=AAAAA
ComputeDigestCodebase.CodeBase.4.26=httpmd:empty_file;md5=AAAAA,comments httpmd:empty_file;md5=AAAAA
ComputeDigestCodebase.CodeBase.4.27=httpmd:empty_file;md5=AAAAA,comments httpmd:/empty_file;md5=AAAAA


#        ComputeDigestCodebase.5.* Tests
ComputeDigestCodebase.SrcDir.5=${com.sun.jini.test.home}$/lib
ComputeDigestCodebase.SrcDir.5.1=${ComputeDigestCodebase.SrcDir.5}
ComputeDigestCodebase.SrcDir.5.2=${ComputeDigestCodebase.SrcDir.5}
ComputeDigestCodebase.SrcDir.5.3=${ComputeDigestCodebase.SrcDir.5}
ComputeDigestCodebase.SrcDir.5.4=${ComputeDigestCodebase.SrcDir.5}
ComputeDigestCodebase.SrcDir.5.5=${ComputeDigestCodebase.SrcDir.5}
ComputeDigestCodebase.SrcDir.5.6=${ComputeDigestCodebase.SrcDir.5}
ComputeDigestCodebase.SrcDir.5.7=${ComputeDigestCodebase.SrcDir.5}
ComputeDigestCodebase.SrcDir.5.8=${ComputeDigestCodebase.SrcDir.5}
ComputeDigestCodebase.SrcDir.5.9=${ComputeDigestCodebase.SrcDir.5}
ComputeDigestCodebase.SrcDir.5.10=${ComputeDigestCodebase.SrcDir.5}
ComputeDigestCodebase.SrcDir.5.11=${ComputeDigestCodebase.SrcDir.5}
ComputeDigestCodebase.SrcDir.5.12=${ComputeDigestCodebase.SrcDir.5}
ComputeDigestCodebase.SrcDir.5.13=${ComputeDigestCodebase.SrcDir.5}
ComputeDigestCodebase.SrcDir.5.14=${ComputeDigestCodebase.SrcDir.5}
ComputeDigestCodebase.Expected.5=java.lang.IllegalArgumentException
ComputeDigestCodebase.Expected.5.1=${ComputeDigestCodebase.Expected.5}
ComputeDigestCodebase.Expected.5.2=${ComputeDigestCodebase.Expected.5}
ComputeDigestCodebase.Expected.5.3=${ComputeDigestCodebase.Expected.5}
ComputeDigestCodebase.Expected.5.4=${ComputeDigestCodebase.Expected.5}
ComputeDigestCodebase.Expected.5.5=${ComputeDigestCodebase.Expected.5}
ComputeDigestCodebase.Expected.5.6=${ComputeDigestCodebase.Expected.5}
ComputeDigestCodebase.Expected.5.7=${ComputeDigestCodebase.Expected.5}
ComputeDigestCodebase.Expected.5.8=${ComputeDigestCodebase.Expected.5}
ComputeDigestCodebase.Expected.5.9=${ComputeDigestCodebase.Expected.5}
ComputeDigestCodebase.Expected.5.10=${ComputeDigestCodebase.Expected.5}
ComputeDigestCodebase.Expected.5.11=${ComputeDigestCodebase.Expected.5}
ComputeDigestCodebase.Expected.5.12=${ComputeDigestCodebase.Expected.5}
ComputeDigestCodebase.Expected.5.13=${ComputeDigestCodebase.Expected.5}
ComputeDigestCodebase.Expected.5.14=${ComputeDigestCodebase.Expected.5}
ComputeDigestCodebase.CodeBase.5.1=qa1-httpmd.jar;md5=AAAAA
ComputeDigestCodebase.CodeBase.5.2=/qa1-httpmd.jar;md5=AAAAA
ComputeDigestCodebase.CodeBase.5.3=file:qa1-httpmd.jar;md5=AAAAA
ComputeDigestCodebase.CodeBase.5.4=file:$/qa1-httpmd.jar;md5=AAAAA
ComputeDigestCodebase.CodeBase.5.5=http:qa1-httpmd.jar;md5=AAAAA
ComputeDigestCodebase.CodeBase.5.6=http:/qa1-httpmd.jar;md5=AAAAA
ComputeDigestCodebase.CodeBase.5.7=http:/qa1-httpmd.jar;md5=AAAAA httpmd:/qa1-httpmd.jar;md5=AAAAA
ComputeDigestCodebase.CodeBase.5.8=http:qa1-httpmd.jar;md5=AAAAA httpmd:qa1-httpmd.jar;md5=AAAAA
ComputeDigestCodebase.CodeBase.5.9=httpmd:/qa1-httpmd.jar;md5=AAAAA http:/qa1-httpmd.jar;md5=AAAAA
ComputeDigestCodebase.CodeBase.5.10=httpmd:qa1-httpmd.jar;md5=AAAAA http:qa1-httpmd.jar;md5=AAAAA
ComputeDigestCodebase.CodeBase.5.11=file:$/qa1-httpmd.jar;md5=AAAAA httpmd:/qa1-httpmd.jar;md5=AAAAA
ComputeDigestCodebase.CodeBase.5.12=file:qa1-httpmd.jar;md5=AAAAA httpmd:qa1-httpmd.jar;md5=AAAAA
ComputeDigestCodebase.CodeBase.5.13=httpmd:/qa1-httpmd.jar;md5=AAAAA file:$/qa1-httpmd.jar;md5=AAAAA
ComputeDigestCodebase.CodeBase.5.14=httpmd:qa1-httpmd.jar;md5=AAAAA file:qa1-httpmd.jar;md5=AAAAA


#        ComputeDigestCodebase.6.* Tests
ComputeDigestCodebase.SrcDir.6=${java.io.tmpdir}
ComputeDigestCodebase.SrcDir.6.1=${ComputeDigestCodebase.SrcDir.6}
ComputeDigestCodebase.SrcDir.6.2=${ComputeDigestCodebase.SrcDir.6}
ComputeDigestCodebase.SrcDir.6.3=${ComputeDigestCodebase.SrcDir.6}
ComputeDigestCodebase.SrcDir.6.4=${ComputeDigestCodebase.SrcDir.6}
ComputeDigestCodebase.Expected.6=java.io.IOException
ComputeDigestCodebase.Expected.6.1=${ComputeDigestCodebase.Expected.6}
ComputeDigestCodebase.Expected.6.2=${ComputeDigestCodebase.Expected.6}
ComputeDigestCodebase.Expected.6.3=${ComputeDigestCodebase.Expected.6}
ComputeDigestCodebase.Expected.6.4=${ComputeDigestCodebase.Expected.6}
ComputeDigestCodebase.CodeBase.6.1=httpmd:non-exist;md5=AAAAA
ComputeDigestCodebase.CodeBase.6.2=httpmd:/non-exist;md5=AAAAA
ComputeDigestCodebase.CodeBase.6.3=httpmd://localhost/non-exist;md5=AAAAA
ComputeDigestCodebase.CodeBase.6.4=httpmd://localhost:1111/non-exist;md5=AAAAA


#        ComputeDigestCodebase.7.* Tests
ComputeDigestCodebase.CodeBase.7=httpmd:qa1-httpmd.jar;md5=AAAAA
ComputeDigestCodebase.CodeBase.7.1=${ComputeDigestCodebase.CodeBase.7}
ComputeDigestCodebase.CodeBase.7.2=${ComputeDigestCodebase.CodeBase.7}
ComputeDigestCodebase.Expected.7=java.io.IOException
ComputeDigestCodebase.Expected.7.1=${ComputeDigestCodebase.Expected.7}
ComputeDigestCodebase.Expected.7.2=${ComputeDigestCodebase.Expected.7}
ComputeDigestCodebase.SrcDir.7.1=${com.sun.jini.test.home}$/lib${file.separator}qa1-httpmd.jar
ComputeDigestCodebase.SrcDir.7.2=${file.separator}non-exist-dir


#        ComputeDigestCodebase.8.* Tests
ComputeDigestCodebase.SrcDir.8=${com.sun.jini.test.home}$/lib
ComputeDigestCodebase.SrcDir.8.1=${ComputeDigestCodebase.SrcDir.8}
ComputeDigestCodebase.SrcDir.8.2=${ComputeDigestCodebase.SrcDir.8}
ComputeDigestCodebase.SrcDir.8.3=${ComputeDigestCodebase.SrcDir.8}
ComputeDigestCodebase.SrcDir.8.4=${ComputeDigestCodebase.SrcDir.8}
ComputeDigestCodebase.SrcDir.8.5=${ComputeDigestCodebase.SrcDir.8}
ComputeDigestCodebase.SrcDir.8.6=${ComputeDigestCodebase.SrcDir.8}
ComputeDigestCodebase.SrcDir.8.7=${ComputeDigestCodebase.SrcDir.8}
ComputeDigestCodebase.SrcDir.8.8=${ComputeDigestCodebase.SrcDir.8}
ComputeDigestCodebase.SrcDir.8.9=${ComputeDigestCodebase.SrcDir.8}
ComputeDigestCodebase.SrcDir.8.10=${ComputeDigestCodebase.SrcDir.8}
ComputeDigestCodebase.SrcDir.8.11=${ComputeDigestCodebase.SrcDir.8}
ComputeDigestCodebase.SrcDir.8.12=${ComputeDigestCodebase.SrcDir.8}
ComputeDigestCodebase.SrcDir.8.13=${ComputeDigestCodebase.SrcDir.8}
ComputeDigestCodebase.SrcDir.8.14=${ComputeDigestCodebase.SrcDir.8}
ComputeDigestCodebase.SrcDir.8.15=${ComputeDigestCodebase.SrcDir.8}
ComputeDigestCodebase.SrcDir.8.16=${ComputeDigestCodebase.SrcDir.8}
ComputeDigestCodebase.Expected.8=java.net.MalformedURLException
ComputeDigestCodebase.Expected.8.1=${ComputeDigestCodebase.Expected.8}
ComputeDigestCodebase.Expected.8.2=${ComputeDigestCodebase.Expected.8}
ComputeDigestCodebase.Expected.8.3=${ComputeDigestCodebase.Expected.8}
ComputeDigestCodebase.Expected.8.4=${ComputeDigestCodebase.Expected.8}
ComputeDigestCodebase.Expected.8.5=${ComputeDigestCodebase.Expected.8}
ComputeDigestCodebase.Expected.8.6=${ComputeDigestCodebase.Expected.8}
ComputeDigestCodebase.Expected.8.7=${ComputeDigestCodebase.Expected.8}
ComputeDigestCodebase.Expected.8.8=${ComputeDigestCodebase.Expected.8}
ComputeDigestCodebase.Expected.8.9=${ComputeDigestCodebase.Expected.8}
ComputeDigestCodebase.Expected.8.10=${ComputeDigestCodebase.Expected.8}
ComputeDigestCodebase.Expected.8.11=${ComputeDigestCodebase.Expected.8}
ComputeDigestCodebase.Expected.8.12=${ComputeDigestCodebase.Expected.8}
ComputeDigestCodebase.Expected.8.13=${ComputeDigestCodebase.Expected.8}
ComputeDigestCodebase.Expected.8.14=${ComputeDigestCodebase.Expected.8}
ComputeDigestCodebase.Expected.8.15=${ComputeDigestCodebase.Expected.8}
ComputeDigestCodebase.Expected.8.16=${ComputeDigestCodebase.Expected.8}
ComputeDigestCodebase.CodeBase.8.1=httpmd:qa1-httpmd.jar
ComputeDigestCodebase.CodeBase.8.2=httpmd:qa1-httpmd.jar,comments
ComputeDigestCodebase.CodeBase.8.3=httpmd:/qa1-httpmd.jar
ComputeDigestCodebase.CodeBase.8.4=httpmd:/qa1-httpmd.jar,comments
ComputeDigestCodebase.CodeBase.8.5=httpmd:qa1-httpmd.jar;
ComputeDigestCodebase.CodeBase.8.6=httpmd:qa1-httpmd.jar;,comments
ComputeDigestCodebase.CodeBase.8.7=httpmd:/qa1-httpmd.jar;
ComputeDigestCodebase.CodeBase.8.8=httpmd:/qa1-httpmd.jar;,comments
ComputeDigestCodebase.CodeBase.8.9=httpmd:qa1-httpmd.jar;md5
ComputeDigestCodebase.CodeBase.8.10=httpmd:qa1-httpmd.jar;md5,comments
ComputeDigestCodebase.CodeBase.8.11=httpmd:/qa1-httpmd.jar;md5
ComputeDigestCodebase.CodeBase.8.12=httpmd:/qa1-httpmd.jar;md5,comments
ComputeDigestCodebase.CodeBase.8.13=httpmd:qa1-httpmd.jar;md5=
ComputeDigestCodebase.CodeBase.8.14=httpmd:qa1-httpmd.jar;md5=,comments
ComputeDigestCodebase.CodeBase.8.15=httpmd:/qa1-httpmd.jar;md5=
ComputeDigestCodebase.CodeBase.8.16=httpmd:/qa1-httpmd.jar;md5=,comments


#        ComputeDigestCodebase.9.* Tests
ComputeDigestCodebase.SrcDir.9=${com.sun.jini.test.home}$/lib
ComputeDigestCodebase.SrcDir.9.1=${ComputeDigestCodebase.SrcDir.9}
ComputeDigestCodebase.Expected.9=java.lang.NullPointerException
ComputeDigestCodebase.Expected.9.1=${ComputeDigestCodebase.Expected.9}


#        ComputeDigestCodebase.10.* Tests
ComputeDigestCodebase.Expected.10=java.lang.NullPointerException
ComputeDigestCodebase.Expected.10.1=${ComputeDigestCodebase.Expected.10}
ComputeDigestCodebase.CodeBase.10=httpmd:/qa1-httpmd.jar;md5=AAAAA,comments
ComputeDigestCodebase.CodeBase.10.1=${ComputeDigestCodebase.CodeBase.10}


#        ComputeDigestCodebase.11.* Tests
ComputeDigestCodebase.Expected.11=java.lang.NullPointerException
ComputeDigestCodebase.Expected.11.1=${ComputeDigestCodebase.Expected.11}
include0=../../url.properties
