
#/*
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#*/


# Individual classes that need to be placed in the downloadable jar file

QASHARE_JARS = qa1-share-dl.jar qa1-reggie-race.jar qa1-reggie-race-dl.jar

QAJARS     +=	$(QASHARE_JARS)

qa1-share-dl.jar: jartools
	rm -f $(QAJARSDIR)/$@
	@echo Creating $@
	@cd $(CLASSDIR); $(JAR) cf $(QAJARSDIR)/$@ `$(QACLASSDEP) -in com.sun.jini.test com.sun.jini.test.share.reggie.RegistrarProxy com.sun.jini.test.share.reggie.RegistrarAdminProxy com.sun.jini.test.share.reggie.EventLease com.sun.jini.test.share.reggie.Registration com.sun.jini.test.share.reggie.RegistrarEvent com.sun.jini.test.share.AttrOne com.sun.jini.test.share.AttrTwo com.sun.jini.test.share.SunOfAttrOne com.sun.jini.test.share.TestLease com.sun.jini.test.share.ConstrainableTestLease com.sun.jini.test.share.ConstrainableUnreadableTestLease com.sun.jini.test.share.TesterTransactionManagerProxy com.sun.jini.test.share.TesterTransactionManagerConstrainableProxy com.sun.jini.test.share.TesterTransactionManagerProxyVerifier com.sun.jini.test.share.LeaseBackEndImpl'$$'VerifierImpl $(subst $$,'$$',$(QASHARE.impls:%=%_Stub))`
	@cd $(JINICLASSES); $(JAR) uf $(QAJARSDIR)/$@ `$(QACLASSDEP) -in com.sun.jini -in net.jini $(JSKPLATFORM.EXCLUDE) -hide com.sun.jini.test com.sun.jini.test.share.reggie.RegistrarProxy com.sun.jini.test.share.reggie.RegistrarAdminProxy com.sun.jini.test.share.reggie.EventLease com.sun.jini.test.share.reggie.Registration com.sun.jini.test.share.reggie.RegistrarEvent com.sun.jini.test.share.TesterTransactionManagerProxy com.sun.jini.test.share.TesterTransactionManagerConstrainableProxy com.sun.jini.test.share.TesterTransactionManagerProxyVerifier com.sun.jini.proxy.BasicProxyTrustVerifier $(subst $$,'$$',$(QASHARE.impls:%=%_Stub))`


qa1-reggie-race.jar:
	rm -f $(QAJARSDIR)/$@
	@echo creating $@
	$(qa.link)
	@cd $(JINICLASSES); $(JAR) cf $(QAJARSDIR)/$@ `$(QACLASSDEP) -in net.jini -in com.sun.jini com.sun.jini.test.share.reggie.RegistrarImpl com.sun.jini.test.share.reggie.CreateLookup $(subst $$,'$$',$(QASHARE.impls:%=%_Stub))` com/sun/jini/start/resources
	$(qa.unlink)

qa1-reggie-race-dl.jar:
	rm -f $(QAJARSDIR)/$@
	@echo creating $@
	$(qa.link)
	@cd $(JINICLASSES); $(JAR) cf $(QAJARSDIR)/$@ `$(QACLASSDEP) -in net.jini -in com.sun.jini com.sun.jini.test.share.reggie.RegistrarProxy com.sun.jini.test.share.reggie.RegistrarAdminProxy com.sun.jini.test.share.reggie.EventLease com.sun.jini.test.share.reggie.Registration com.sun.jini.test.share.reggie.RegistrarEvent net.jini.lookup.entry.Name net.jini.lookup.entry.ServiceInfo com.sun.jini.lookup.entry.BasicServiceType com.sun.jini.reliableLog.LogException $(subst $$,'$$',$(QASHARE.impls:%=%_Stub))`
	$(qa.unlink)
