#/*
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#*/


# Individual classes that need to be placed in the jar file

#QALOADER_PREF_JARS = qa1-loader-pref.jar \
#		      qa1-loader-pref-NO-PREFERRED-LIST.jar

QALOADER_PREF_JARS = qa1-loader-pref.jar

QAJARS       +=	$(QALOADER_PREF_JARS)

PREFCLASSES     =	com/sun/jini/test/spec/loader/util/classes
PREFRESOURCES   =	com/sun/jini/test/spec/loader/util/resources
CLASSES_LOCAL   =	com/sun/jini/test/spec/loader/util/classes_local
RESOURCES_LOCAL =	com/sun/jini/test/spec/loader/util/resources_local
VOBPLACE	=	${VIEW_ROOT}

qa1-loader-pref.jar: jartools
	rm -f $(QAJARSDIR)/$@
	@echo Creating $@
	@cd $(VOBPLACE)/vob/qa/src/$(PREFCLASSES); $(JAR) cf $(QAJARSDIR)/$@ META-INF/PREFERRED.LIST
	@cd $(VOBPLACE)/vob/qa/src; $(JAR) uf $(QAJARSDIR)/$@ $(PREFRESOURCES)
	@cd $(CLASSDIR); $(JAR) uf $(QAJARSDIR)/$@ $(PREFCLASSES)
