testClass=GrantNoPrincipalCase02
testCategories=policyprovider,policyprovider_spec
testPolicyfile=policyProviderGrant01.policy
com.sun.jini.qa.harness.runkitserver=false 
com.sun.jini.qa.harness.runjiniserver=false
com.sun.jini.qa.harness.securityproperties=<url: ../securityprovider.properties>
#testjvmargs=\
#-Xdebug,\
#-Xrunjdwp:transport=dt_socket+,address=8000+,server=y+,suspend=y,\
#${testjvmargs}
