testClass=SecurityExceptionConstructor
testCategories=policyprovider,policyprovider_spec
testPolicyfile=policyProviderNoAccessClass.policy
com.sun.jini.qa.harness.runkitserver=false 
com.sun.jini.qa.harness.runjiniserver=false
com.sun.jini.qa.harness.securityproperties=<url: securityexceptionconstructornoaccessclass.properties>
#com.sun.jini.qa.harness.securityproperties=<url: ../securityprovider.properties>
