testClass=MailboxImplNullConfigEntries
testCategories=eventmailbox,eventmailbox_impl

net.jini.event.EventMailbox.instances=6

net.jini.event.EventMailbox.override.0=com.sun.jini.mercury.serverExporter=null
net.jini.event.EventMailbox.override.1=com.sun.jini.mercury.initialLookupAttributes=null
net.jini.event.EventMailbox.override.2=com.sun.jini.mercury.initialLookupLocators=null
net.jini.event.EventMailbox.override.3=com.sun.jini.mercury.leasePeriodPolicy=null
net.jini.event.EventMailbox.override.4=com.sun.jini.mercury.listenerPreparer=null
net.jini.event.EventMailbox.override.5=com.sun.jini.mercury.locatorToJoinPreparer=null
include0=mercury.properties
