#/*
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#*/



QALOOKUPSERVICE.impls	= com.sun.jini.test.spec.lookupservice.test_set00.EvntLeaseExpiration$$Listener         \
                          com.sun.jini.test.spec.lookupservice.test_set00.NotifyOnAttrAdd$$Listener             \
                          com.sun.jini.test.spec.lookupservice.test_set00.NotifyOnAttrMod$$Listener             \
                          com.sun.jini.test.spec.lookupservice.test_set00.NotifyOnAttrDel$$Listener             \
                          com.sun.jini.test.spec.lookupservice.test_set00.NotifyOnSrvcLeaseExpiration$$Listener \
                          com.sun.jini.test.spec.lookupservice.test_set00.MultipleEvntLeaseRenewals$$Listener   \
                          com.sun.jini.test.spec.lookupservice.test_set01.NotifyOnComboAttrAddNull$$Listener    \
                          com.sun.jini.test.spec.lookupservice.test_set01.NotifyOnComboAttrAddNonNull$$Listener \
                          com.sun.jini.test.spec.lookupservice.test_set01.NotifyOnComboAttrModNull$$Listener    \
                          com.sun.jini.test.spec.lookupservice.test_set01.NotifyOnComboAttrModNonNull$$Listener \
                          com.sun.jini.test.spec.lookupservice.test_set01.NotifyOnComboAttrDelNull$$Listener    \
                          com.sun.jini.test.spec.lookupservice.test_set01.NotifyOnComboAttrDelNonNull$$Listener \
                          com.sun.jini.test.spec.lookupservice.test_set01.NotifyOnComboSrvcReg$$Listener        \
                          com.sun.jini.test.spec.lookupservice.test_set01.NotifyOnComboSrvcLeaseExp$$Listener   \
                          com.sun.jini.test.spec.lookupservice.test_set01.NotifyOnEntrySrvcReg$$Listener        \
                          com.sun.jini.test.spec.lookupservice.test_set01.NotifyOnEntryAttrAddNull$$Listener    \
                          com.sun.jini.test.spec.lookupservice.test_set01.NotifyOnEntryAttrAddNonNull$$Listener \
                          com.sun.jini.test.spec.lookupservice.test_set02.LeaseMapRenew$$Listener               \
                          com.sun.jini.test.spec.lookupservice.test_set02.LeaseMapCancel$$Listener              \
                          com.sun.jini.test.spec.lookupservice.test_set02.ExpiredEventLeaseRenew$$Listener      \
                          com.sun.jini.test.spec.lookupservice.test_set02.ExpiredEventLeaseCancel$$Listener     \
                          com.sun.jini.test.spec.lookupservice.test_set02.ExpiredLeaseMapRenew$$Listener        \
                          com.sun.jini.test.spec.lookupservice.test_set02.ExpiredLeaseMapCancel$$Listener       \
                          com.sun.jini.test.spec.lookupservice.test_set02.NotifyOnAttrSet$$Listener             \
                          com.sun.jini.test.spec.lookupservice.test_set02.NotifyOnComboAttrSet$$Listener        \
                          com.sun.jini.test.spec.lookupservice.test_set02.NotifyExceptionTest$$Listener

SERVER.class +=	$(QALOOKUPSERVICE.impls)



